### PR TITLE
[Testing] xivr 0.0.0.10

### PR DESCRIPTION
**Pull request by ProjectMimer**
Updated to 6.3
Added head based locomotion
Added vertical locomotion

### CODE REVIEW

**Comment by NotNite** [comment]
You seem to have two PRs open?

**Comment by ProjectMimer** [comment]
so the system dosent auto close/cancel the request when it fails to build?

**Comment by NotNite** [comment]
It does not. You push extra commits to the pull request until it builds, and then wait for approval.

**Comment by goaaats** [comment]
bleatbot, rebuild

**Review by goaaats — APPROVED** [review]

**Pull request merged**
