### PR TITLE
[Testing] Altoholic 0.0.0.2

### PR DESCRIPTION
**Pull request by Sohtoren**
Information about your alts : get gils, currencies, inventory and retainers items from all your characters

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by Sohtoren** [comment]
Sorry for the big change since the first commit. Updated for DT and adding a bunch of new things like inventories or collected things.

**Comment by Sohtoren** [comment]
Small fix for a regression on currencies

**Comment by reiichi001** [comment]
Some of the text gets cut off. Not a dealbreaker for testing release, but something to fix for stable.
image

**Comment by Sohtoren** [comment]
> Some of the text gets cut off. Not a dealbreaker for testing release, but something to fix for stable.

Yes, I've mainly put thing in place but any visual style and overall tooltip placements will be done once everything has been implemented. I'm mainly looking at (users) feedback about how things are presented for the testing phase.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by Sohtoren** [comment]
It's the same name

**Pull request merged**
