### PR TITLE
[Testing] CharacterSelectBackgroundPlugin v0.0.2.0

### PR DESCRIPTION
**Pull request by RokasKil**
Immersive Character Select is a plugin that allows you to replace the default character select scene with a custom one.

- Records your last location or allows to setup a preset, allows you to mount up in character select screen (presets only allow you to select mounts from your unlocked list)
- Functions mostly by interacting with `AgentLobby` and `LobbyCamera` stuff, affects only character select screen
- Has some janky `LayoutManager` data saving to restore zone details in character select, hoping to remove some of the included structs once Dalamud gets the new FFXIVClientStructs stuff (the included ones are taken from a PR to CS) and in general rework and optimize it somewhat
- From my personal testing it's stable and I haven't experienced any crashes or performance issues caused by the constant character recording

Not expecting for this to be reviewed before DT but maybe I'll get some remarks and what not before having to redo everything and upgrade to apiX

### CODE REVIEW

**Comment by RokasKil** [comment]
bleatbot, rebuild

**Comment by RokasKil** [comment]
bleatbot, rebuild

**Comment by lmcintyre** [comment]
As a PAC member, hi! Thanks for your plugin submission.

As a fellow plugin dev, considering the feature similarity, I'd like to ask if you'd consider maintaining the Title Edit plugin and merging the feature set into a single plugin.

**Comment by RokasKil** [comment]
Hi, yes, I think I could adopt TitleEdit as a whole, updating it for DT and then doing a rewrite with this plugin as a base (assuming I can figure out the headache that is layout saving/reloading to a good enough degree)

**Comment by RokasKil** [comment]
Closing since this will eventually be merged into TitleEdit

**Pull request closed without merging**
