### PR TITLE
[Testing] SimpleMarketBoard 1.2.0.2

### PR DESCRIPTION
**Pull request by Elypha**
Helllo,

In this PR:

- a minor version update that resolves a new warning since the last dalamud update.
- copy manifest to `main`

In the testing so far the plugin seems to be fine, so I think it might be time to release it under `main`. I'm not sure if I'm doing this properly so please let me know if there's anything I can improve.

### CODE REVIEW

**Comment by Elypha** [comment]
hmmm for the compiling issue, am I not supposed to use the same hash for stable and testing/live?

**Comment by philpax** [comment]
Ah, that's a recently introduced issue. @goaaats is fixing it and should have this sorted out for you soon.

**Comment by Elypha** [comment]
testing version advanced 1 for the sake of the compiler xx

**Review by philpax — APPROVED** [review]
goat wasn't able to make time to fix the issue, so I'll just merge your version bump. Thanks for doing that - I'll make an issue for it so that it can be fixed at some later stage!

**Pull request merged**
