### PR TITLE
[Testing] DragoonMayCry v0.4.2

### PR DESCRIPTION
**Pull request by Felscream**
It's a plugin that tries to add flavour to the game combat by adding a style system inspired by the Devil May Cry series.

- There are 8 tiers : unranked, D, C, B, A, S, SS, SSS
- You score by dealing damage
- You go to the next tier if your score passes a certain threshold, a sound effect can be played if activated in the settings
- You lose points overtime
- The amount of points gained is reduced if you clip your GCD
- You go back to the previous tier if your score is under a threshold for a set amount of time, or you stop rolling your GCD.
- Casting a Limit Break charges your gauge.
- Dying or cancelling a limit break cast sets you to D

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by Felscream** [comment]
Just read that I can't use NAudio.Wave due to it's dependencies. I'll try to remove it

**Comment by Felscream** [comment]
Looks like I was already using NAudio 2.2.1 when the build failed. I don't know why the dependency doesn't appear on their side, but it does on mine. I just tested locally.

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by Critical-Impact** [comment]
Test Results:
Plugin loads properly
A window pops up automatically that I can't remove until locking it in the config(a little unintuitive)
I set it to be active outside an instance and tried to attack a striking dummy and nothing showed up
I tried to unlock the score window and my log was spammed with these errors
```
18:41:42.290 | ERR | Exception during raise of "Void DrawUI()"
	System.Collections.Generic.KeyNotFoundException: The given key 'NoStyle' was not present in the dictionary.
	   at DragoonMayCry.UI.StyleRankUI.DrawMock(ImGuiWindowFlags windowFlags) in /work/repo/DragoonMayCry/UI/StyleRankUI.cs:line 158
	   at DragoonMayCry.UI.StyleRankUI.Draw() in /work/repo/DragoonMayCry/UI/StyleRankUI.cs:line 109
	   at DragoonMayCry.UI.PluginUI.DrawUI() in /work/repo/DragoonMayCry/UI/PluginUI.cs:line 63
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

**Comment by Felscream** [comment]
I'll look it up

**Comment by Felscream** [comment]
Errors should be fixed with this version. You may need to delete the plugin conf file if you want to retest installation.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
