### PR TITLE
[Testing] Add MiniMappingway

### PR DESCRIPTION
**Pull request by jaycewhite**

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on submitting your first plugin!

**Comment by philpax** [comment]
If you're in the Goat Place Discord, let me know what your Discord username is and I'll have you added to the dev channels.

**Pull request merged**
