### PR TITLE
[Testing] Map Party Assist

### PR DESCRIPTION
**Pull request by wrath16**
Map Party Assist is a fairly simple plugin that tracks treasure map usage and records treasure dungeon statistics to make the process of running treasure maps as a party smoother.

The core functionality works by processing chat messages and it only uses exposed Dalamud services (for now). It also does not modify any game data or make server requests. Data is stored in a LiteDB instance.

It's already in use by players in the treasure map/achievement hunting communities through my custom repo, but I'd like to make it available to a wider audience.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by wrath16** [comment]
bleatbot, rebuild

**Comment by wrath16** [comment]
Thanks for the response. Unfortunately it will take me some time to add non-English support because:

1. The strings used for parsing do not appear to be readily available in the data sheets. (server or script generated?)
2.  Some of the events are of extremely low probability and would take perhaps dozens to hundreds of hours to reproduce in all languages.
3. I don't have a working knowledge of French/German/Japanese.

**Comment by wrath16** [comment]
An example would be "The cages are empty." which is a system message that occurs after clearing all enemies in a chamber for most of the treasure map dungeons. I'm using [Alpha](https://github.com/NotNite/Alpha) to browse the Excel sheets and searching turns up nothing.

**Comment by Aireil** [comment]
It's in the `LogMessage` sheet row 3777 and 3800.

**Comment by Aireil** [comment]
You can right click the sheet search in Alpha to swap to "search sheets that contain this string". Nearly all localized strings are in the sheets somewhere ^^.

**Comment by wrath16** [comment]
Huh, that's strange I had been doing a full text search but it never came up. Thanks so much this will be very helpful!

**Comment by Aireil** [comment]
> You can right click the sheet search in Alpha to swap to "search sheets that contain this string". Nearly all localized strings are in the sheets somewhere ^^.

I said that because Nite told me, but after testing, it doesn't seem to work for me, so huh, not sure how you do that! hehe

**Comment by NotNite** [comment]
oops :P

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
Testing looks good as of build 7412f0c. Any new builds will involve testing again.

As stated by @lmcintyre, changes to accommodate all global client languages are needed, but it looks like that's been addressed by prior conversation and is just awaiting a new build.

**Comment by wrath16** [comment]
Hey, apologies for the delay. I have it working for all of the international client languages (EN/FR/DE/JP) and am just testing and cleaning things up right now. Will update the PR later this week.

**Comment by karashiiro** [comment]
Assigning myself for code review.

**Comment by reiichi001** [comment]
Diff between last reviewed version and current: https://github.com/wrath16/MapPartyAssist/compare/61e2a215b83bcbc21038ac6359d90414f7fc2ac3..997f147052fe90fedc31d30e2d8b70703270d521

Based on this, code looks fine.

**Comment by karashiiro** [comment]
Handed off to Franz, just one general comment to make: There are at least a couple cases like [here](https://github.com/wrath16/MapPartyAssist/blob/997f147052fe90fedc31d30e2d8b70703270d521/MapPartyAssist/Windows/ViewDutyResultsImportsWindow.cs#L37) where `SemaphoreSlim.Wait` is being called in a task, which blocks the thread running the task and prevents it from being used by tasks initiated by other plugins or by Dalamud itself. Minor performance impact as far as I can tell but worth noting — the easy way to fix that is to just replace calls to `Wait` inside tasks with `await _lock.WaitAsync()`. Non-critical issue, fine to merge with this.

**Comment by reiichi001** [comment]
Re-test of MapPartyAssist-997f147052fe90fedc31d30e2d8b70703270d521 is good.

**Review by philpax — APPROVED** [review]

**Pull request merged**
