### PR TITLE
Update Peeping Tom

### PR DESCRIPTION
**Pull request by ascclemens**
- Fixed the crash when using Alt-click to examine.

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by ascclemens** [comment]
Do I need to do anything about this

**Comment by goaaats** [comment]
Nope, working on changelogs, will merge in a bit

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Review by goaaats — APPROVED** [review]

**Pull request merged**
