### PR TITLE
SonarPlugin v0.5.2.6

### PR DESCRIPTION
**Pull request by rreminy**
DIP17 test

### CODE REVIEW

**Comment by philpax** [comment]
The bot needs to be able to see the source code in order to build it. I don't think we have a solution for you yet, unfortunately.

**Comment by rreminy** [comment]
goat is working on it

**Comment by Caraxi** [comment]
could easily fix yourself by making it open source like all plugins should be

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by rreminy** [comment]
This doesn't look like its something I can fix on my side

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by rreminy** [comment]
So far I removed LoycCore and NonBlocking from SonarDistrib. I'll be checking what other components I can remove as well to make the code-base lighter as requested. The status of the other components are:

**System.Management**: This is a direct copy-and-paste of the actual code-base. Trying to include the nuget package, due to how Sonar is compiled, will pull the wrong one, which doesn't work. This is in use for hardware identifiers. Unless they change how packages are pulled, there are no plans on removing this component.
**DeviceId.Windows.Wmi**: Likewise as System.Management, this is another direct copy-and-paste. Pulling the nuget version will result in using the wrong System.Management from nuget, which won't work. Unless the situation changes, there are no plans to remove this component.
**XoshiroPRNG.Net**: Slightly modified to support Span<T>. I'll be taking a look to see if removal of this component is possible, in favor of the nuget one. Currently in use at the server.
**IPAddressRange**: Slightly modified to expose some internals. This is in use by the server for IP address rules, should the need arise.
**Collections.Pooled**: The only usage of this I can remember are in the sockets. I'll take a look and see if removal is possible.

Note that this month is busy for me so my availability is limited, however I'll be working on this while I'm able.

**Comment by rreminy** [comment]
After so much I said there are no plans to remove, `System.Management.dll`, and by extension. `DeviceId.Windows.Wmi` has been removed. Thanks to Meoiswa and KazWolfe on discord for helping me with this.

**Comment by rreminy** [comment]
I managed to remove all the extra libraries from being built, reducing the code-base to compile from 281k to just 25k.

**Comment by rrbailey89** [comment]
wow PR open 7 months, looks like the DEV has done a considerable amount of work and put a lot of effort to get it merged... all the while leaving comments and getting no responses.. is there something holding up the merging of this plogon?

**Comment by NotNite** [comment]
> wow PR open 7 months, looks like the DEV has done a considerable amount of work and put a lot of effort to get it merged... all the while leaving comments and getting no responses.. is there something holding up the merging of this plogon?

@rrbailey89 There's a long story here, but the TLDR is that Sonar was originally closed source, and they are the last plugin to migrate to DIP17. Because of the quirks with their project and it's dependencies, we need to take a lot of care in getting everything working with DIP17.

There doesn't look like any comments in this PR, but there's been a lot of conversations in and out of Discord servers and DMs. We're in touch with the Sonar authors, if that's what you're curious about.

**Review by goaaats — APPROVED** [review]

**Pull request merged**
