### PR TITLE
JobBars v1.2.3.4

### PR DESCRIPTION
**Pull request by 0ceal0t**
- Fixed issues with icons being improperly replaced
- Fixed duration of living shadow
- Fixed divine veil cooldown tracker

### CODE REVIEW

**Comment by goaaats** [comment]
Did you always have binaries for client structs in here? Could you use a submodule instead? If not, why?

**Comment by MidoriKami** [comment]
When 6.3 released, I cloned built and tested Jobbars locally, and removed the reference to ClientStructs and used Dalamuds without issue.

**Comment by 0ceal0t** [comment]
> Did you always have binaries for client structs in here? Could you use a submodule instead? If not, why?

yeah, there were always binaries in there, since sometimes I've need to make custom changes before they've been merged into the main repository

**Comment by philpax** [comment]
blocked on @goaaats's call on what to do

**Comment by 0ceal0t** [comment]
I mean I can remove them since right now CS has everything I need

**Comment by philpax** [comment]
oh sweet then yeah that would be great

**Comment by philpax** [comment]
pingerino

**Comment by 0ceal0t** [comment]
@philpax I removed the CS binaries

**Review by philpax — APPROVED** [review]

**Pull request merged**
