### PR TITLE
NextUIPlugin for patch 6.2

### PR DESCRIPTION
**Pull request by pwilkowski**
Tested on linux and windows clients

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
You'll need to set the owners to your GitHub username.

**Comment by pwilkowski** [comment]
Updated, will that work?

**Comment by NotNite** [comment]
You have permission from the owner/are one of the main developers of NextUI, correct?

**Comment by pwilkowski** [comment]
I am the only developer of it and the only owner, sadly my github username was created long before so i made organization named kaminaris.

**Review by philpax — APPROVED** [review]

**Pull request merged**
