### PR TITLE
[Testing] Minesweeper

### PR DESCRIPTION
**Pull request by hunter2actual**
Hello, this is my first time developing in the Dalamud ecosystem. I have created Minesweeper, in imitation of classic windows versions of the game. Repo link: https://github.com/hunter2actual/DalamudMinesweeper

image

Thank you for your consideration!

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by hunter2actual** [comment]
@ackwell Thanks for picking this up. If you have any questions or would like a walkthrough of my code, let me know. My coding standards were pretty sloppy since this was a solo project but hopefully it's all understandable.

**Comment by philpax** [comment]
Tested by @NotNite. Feedback:
- minor nitpick: the buttons at the bottom could use some tooltips since I had to click them to see what they did (resizing it in the process, making my window super big and having to pan it upwards lol)

**Comment by hunter2actual** [comment]
@philpax @NotNite Good feedback, thank you. Updated.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by hunter2actual** [comment]
@philpax My discord handle is `hunter2_`, I think I have access to some stuff already.
What's the process for going from testing to stable?

**Pull request merged**
