### PR TITLE
[Testing] FakeName 1.2.2

### PR DESCRIPTION
**Pull request by ArchiDog1998**
Change your and the others' names visually.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Sorry for the delay! We're taking this plugin through the review process now and will update as it goes along 🙂

**Comment by ArchiDog1998** [comment]
Hi! This plugin isn't ready for DT expansion. I am waiting for the goatcorp/Dalamud#1915 merging to make it easier to change the name on the NamePlate. Here are the answers. 

- All changes that you make using the plugin are for your client only and other people that you play with or meet in-game will still see your real in-game character name.
- Your character's in-game name can still be tracked by other in-game players or by using other third-party resources so DON'T USE IT TO STREAM as there are people who could track and do harm to you.
- Technically, it displays the fake name by replacing the text in SeString. [These](https://github.com/ArchiDog1998/FakeName/blob/2f7d28ef2b4309aa4b9c66d1541281bd5415a5ec/FakeName/Hooker.cs#L23-L38) are two places to modify game data. So the changed data won't be sent to the server. And it is a purely visual change.

**Comment by philpax** [comment]
Thanks, appreciate it! Looking forward to it 🙂

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by ArchiDog1998** [comment]
Hi, this plugin is DawnTrail ready!

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by haroldiedema** [comment]
This one is consistently silently crashing me to desktop if you give the primary player a name of the maximum amount of characters the input box allows. It does not seem to matter if a first and last name is given. There are no errors in any of the logs, and I'm not getting an exception window. 

You can easily reproduce this at the character selection screen and hovering over your different characters. Feels like an Atk/UI issue.

**Comment by philpax** [comment]
Hi; I'm very sorry about the back-and-forth on this, as well as the time it's taken to reach this conclusion. 

We were initially in favour of merging this, but there were concerns raised by members of the community with regards to its potential for abuse. Based on this, and further internal discussion, we have reached the conclusion that we can't accept this plugin as its potential for abuse outweighs its positive use cases.

We apologise for this outcome and the time it took to reach it, and we hope that you're willing to submit other plugins in future.

**Pull request closed without merging**
