### PR TITLE
[Testing] SimpleTodo

### PR DESCRIPTION
**Pull request by Lunalicious**
Hello everyone!
This is my first time developing a Plugin here, so please let me know if there is anything I might have done wrong :)
This Plugin aims to provide a simple Todo list, since I couldn't find one and a friend asked for it.
I thought why not try and get it out for everyone, so here it is.
Feedback to anything is much appreciated.

Thank youfor your hard work and your consideration

~Luna

### CODE REVIEW

**Comment by Lunalicious** [comment]
As the manifest check just failed: I'm terribly sorry but I have no clue why that happened. Can someone point out the obvious to me?

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by Lunalicious** [comment]
@reiichi001 I feel like the `[plugin]` in line 1 might be the problem here. I'm still very confused

**Comment by Lunalicious** [comment]
Very interesting that it was indeed the `[plugin]` :o Thanks for your patience <3

**Comment by philpax** [comment]
Classic issue, not your fault 😅 

Your text editor saved the file with a [byte-order mark](https://en.wikipedia.org/wiki/Byte_order_mark) at the start of the file, which meant that the TOML reader couldn't parse it. I just edited the file to get rid of that.

**Comment by Lunalicious** [comment]
Damn you Rider! Thanks for figuring that out. I'll see to get that fixed for future contributions

**Comment by reiichi001** [comment]
Testing checks out and this is ready for merge! If you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by philpax** [comment]
Congratulations on your first plugin! As Franz said, please let us know your Discord username if you want access to the private channels 🙂

**Comment by Lunalicious** [comment]
@philpax Thanks a lot! My Discord Username is `lunaneko_`
Once again: Absolutely amazing work you people do <3

**Pull request merged**
