### PR TITLE
[Testing] Update AutoMountBgm (testing/live)

### PR DESCRIPTION
**Pull request by PrincessRTFM**
Automatically turns mount BGM on or off when you use a mount, depending on which mount it is. By default, all mounts enable BGM when used. The command (`/automountbgm`) allows you to configure your current mount to disable it, or re-enable it if you change your mind.

### CODE REVIEW

**Comment by PrincessRTFM** [comment]
FUCK, forgot that I need an image...

**Comment by PrincessRTFM** [comment]
The build produces a valid PNG at `images/icon.png`, copied from the repo's root folder's `images/icon,.png`. What the hell am I doing wrong?

**Comment by PrincessRTFM** [comment]
bleatbot, cancel

**Comment by PrincessRTFM** [comment]
No, huh? Well, it'll be updated in a second by the _new_ new new... new, new? build.

**Comment by lmcintyre** [comment]
Hi! Sorry to disappoint but we have not gotten to this plugin yet, and will likely not be able to review it until after Dalamud API 9 has been released. I would recommend taking the time and swapping to the API 9 branch of Dalamud by using /xlbranch in-game and swapping to v9 so you can test compatibility with your plugin. Once 6.5 releases, you can verify functionality once more and submit a new build.

Thank you and apologies for the delay.

**Comment by PrincessRTFM** [comment]
Ugh, right, the PR action wipes out the icon on first submission... one sec

**Comment by reiichi001** [comment]
I've reviewed the diff from last approval to now. https://github.com/PrincessRTFM/AutoMountBGM/compare/e816023e1f13c91673949275092f4fe7aa93a3d0..fbd01a7a546f6bfd4d7f272e922f4ac5a0b74de5

Code looks good. This is just waiting on a PAC member to test it and if all looks good on that end, it's ready to merge. (It has passed our other parts of review)

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
