### PR TITLE
[Testing] Resizable HUD

### PR DESCRIPTION
**Pull request by Drahsid**
This is a plugin which lets the user manually and particularly reposition and resize UI addons. I made this plugin so that I could make the vanilla castbar larger. I'm sure others will find this useful. The window is a bit programmer-artsy.
I preemptively updated this to API8/NET7.

### CODE REVIEW

**Comment by Drahsid** [comment]
Fixed a bug with out how I was initializing the config

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by Drahsid** [comment]
The versioning issue mentioned in Pull Request #1191  also existed here. I fixed it in this last update.

**Review by philpax — APPROVED** [review]
Nice work, but it'd be nice to have a user-accessible list of HUD items somewhere

**Pull request merged**
