### PR TITLE
Simple Tweaks 1.8.0.0

### PR DESCRIPTION
**Pull request by Caraxi**
- Updates for 6.3
- New Tweak: `Hide Tooltips in Combat` - Allows hiding Action and/or Item tooltips while in combat.
- New Tweak: `Disable Mouse Camera Control` - Disable all control of the camera using the mouse.
- New Tweak: `Combat Movement Type Control` - Set movement type between Standard and Legacy when in/out of combat or when weapon is drawn/sheathed.
- New Tweak: Name Plate Icon Spacing - Increases the distance between status icons and character names on name plates.
- Removed some tweaks

**Changes:**
- [`Custom Free Company Tags`] Add option to hide «»
- [`Quick Sell Items`] Add option to sell from retainer inventory

### CODE REVIEW

**Comment by Caraxi** [comment]
@bleatbot rebuild

**Comment by Caraxi** [comment]
bleatbot, rebuild

**Comment by Caraxi** [comment]
bleatbot, cancel

**Comment by Caraxi** [comment]
bleatbot, rebuild

**Comment by karashiiro** [comment]
bleatbot, rebuild

**Pull request merged**
