### PR TITLE
[Testing] EmoteLog 0.1.0.0

### PR DESCRIPTION
**Pull request by RokasKil**
The plugin's goal is to log emotes targeted at you and display them in a simple window.

The window can be toggled via the `/el` command and the configuration can be accesed through the plugins menu or by passing `config` argument to the `/el` command.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
@Infiziert90 tested this and found it to work well, but noticed that the window's initial size is much too small at 10x10. Can you make that bigger?

**Comment by RokasKil** [comment]
Good catch, fixed it.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the XIVLauncher & Dalamud Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by RokasKil** [comment]
@philpax my discord handle is MFanatik#9741

**Pull request merged**
