### PR TITLE
FlyTextFilter 4.1.0.3

### PR DESCRIPTION
**Pull request by Aireil**
Fix for 6.2, can I have a 🤡 please?

### CODE REVIEW

**Comment by Aireil** [comment]
@github-actions You are bad and you should feel bad! 😔

**Comment by Aireil** [comment]
This will eventually build, I swear!

**Comment by Aireil** [comment]
Well I said eventually, now you are just rude 😢 .

**Comment by AmenneHolelane** [comment]
> Well I said eventually, now you are just rude 😢 .

no u

**Comment by Aireil** [comment]
🤖🔫 CAREFUL

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by Aireil** [comment]
It built, after all these years the impossible has been achieved! I want to thank KazWolfe, Kouzukii for being part of this very reserved club I am now leaving.

**Review by philpax — APPROVED** [review]

**Pull request merged**
