### PR TITLE
[Testing] MacroMate v1.0.5.6

### PR DESCRIPTION
**Pull request by grittyfrog**
# Introduction

Macro Mate lets you store and run an unlimited number of macros. You can also bind macros to normal macro slots.

For example, you can:

- Automatically swap in the correct raid macro when you enter an instance
- Store longer macros and automatically split them across multiple macro slots.
- Use almost any icon in the game for your Macros

# Limitations 

Macro Mate does not extend the macro system in any way and macros are executed identically to the base game.

You can store macros that are longer then 15 lines, but macros must still be executed in 15-line chunks, and longer macros will need to be linked to multiple macro slots.

Macro Mate is not designed for conditional combat actions. Conditions that are primarily used for dynamically swapping combat actions are out of scope and will not be introduced in this plugin.

### CODE REVIEW

**Comment by lmcintyre** [comment]
bleatbot, approve

**Comment by lmcintyre** [comment]
Add .git to the end of your repository URL

**Comment by lmcintyre** [comment]
There seems to be an issue with the macro link interface:
image

**Comment by grittyfrog** [comment]
Looks like I'm missing a `EndSomething()` somewhere, but I'm not getting that issue locally.

Any chance you could send me the `/xllog` when that issue occurs?

**Comment by grittyfrog** [comment]
Ah I see the issue, it doesn't create the `Backups` folder when attempting to save (which happens during Draw). 

I'll put out a fix shortly

**Comment by grittyfrog** [comment]
Fix is up, sorry about that! :slightly_smiling_face:

**Comment by grittyfrog** [comment]
Got a hold of a windows machine and did some more testing. Major changes since 1.0.1.1:

- [Fix backup file format breaking on Windows](https://github.com/grittyfrog/MacroMate/commit/ba1b0fb081a342de159312ae6fc9be70a01579bb)
- [Fix vanilla macro window crash](https://github.com/grittyfrog/MacroMate/commit/bfa6bb2b2e6af040e43f2695a4e5ffbd544d227f)

**Comment by grittyfrog** [comment]
Turns out I lied, and the vanilla macro window crash was caused by a race condition between writing AtkValue's to the window too often, and the window loading for the first time. It should be _actually_ fixed in the version I just published. 

Testing on Windows and Linux indicates it should be properly stable now, but let me know if you find any other issues.

**Comment by reiichi001** [comment]
Preliminary testing as of build f3cb8c6 looks fine. 

I did notice that a user can click on the backups button / try to make a backup / try to open the folder before any backups will be made. ...like when they haven't defined a macro yet. But the moment they do, those features start to work. This is admittedly an edge case that's unlikely to happen since no backup can be made if there's nothing to back up yet, but you could pop a warning or fade the buttons to indicate they're not usable yet.

**Comment by grittyfrog** [comment]
Good idea, I'll tweak the usability of the backup UI today, thanks for the suggestion :slightly_smiling_face:

**Comment by grittyfrog** [comment]
Version 1.0.5.6 includes your suggestions @reiichi001. Thanks again :slightly_smiling_face: 

(Code changes [here](https://github.com/grittyfrog/MacroMate/commit/677b09bcaaa68c735006170830dddc5c6eefd972))

**Comment by reiichi001** [comment]
Retest of MacroMate-4ec74913424a89a4c0007e112bc6e00467971619 is good!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by grittyfrog** [comment]
Thanks! My discord handle is grittyfrog

**Pull request merged**
