### PR TITLE
[Testing] NameplateSignResizer 

### PR DESCRIPTION
**Pull request by FPC-PM**
NameplateSignResizer lets a user resize, move, or hide signs on their or others' nameplates.

### CODE REVIEW

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by lmcintyre** [comment]
Your URL in your manifest is malformed.

**Comment by lmcintyre** [comment]
After some testing, it seems that some nameplate signs will resize back to their original size. I am testing in a zone where I have not done any sidequests, and rapidly moving the camera around with others' signs set to 2.0 will result in the quest markers shifting between 2x scale and the original 1x scale.

**Comment by reiichi001** [comment]
Bleatbot, approve

**Comment by philpax** [comment]
Hi there, just checking on this - this is ready to merge and we've approved it, but you'll need to fix the issues mentioned by @lmcintyre.

**Comment by philpax** [comment]
bleatbot, approve

**Comment by FPC-PM** [comment]
Hey sorry for taking so long! 
1. Fixed problems with manifest.
2. Moved settings for other players under an Experimental Features option with a warning of the buggy behavior until I have time to find a good fix.

**Comment by philpax** [comment]
We're ready to merge, will you reopen the PR?

**Pull request closed without merging**
