### PR TITLE
[Testing] EurekaHelper 0.0.0.1

### PR DESCRIPTION
**Pull request by snooooowy**
Eureka Tracker in a plugin with some QoL features, credits mentioned in plugin menu.

Features include:
- Eureka Tracker built in plugin. [ingame](https://i.imgur.com/T86K6iD.png) vs [website](https://i.imgur.com/06SmDiP.png)
- DateTime display for upcoming important NMs which requires certain weather condition. [picture](https://i.imgur.com/bHU4RZq.png)
- Display NM progress in chat, copies pop NM to clipboard
- Get list of available public eureka trackers

More features to come

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Can you list the features? Helps with the review process :)

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by snooooowy** [comment]
> Can you list the features? Helps with the review process :)

I have updated the main post, thank you.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!
 
As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by snooooowy** [comment]
> Congratulations on your first plugin!
> 
> As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

Yup I'm in the discord, my handle is Snowy#9716

**Pull request merged**
