### PR TITLE
WinTitle v1.0.4.0

### PR DESCRIPTION
**Pull request by rreminy**
API 7

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Change repo from `"https://github.com/rreminy/FFXIV.WinTitle"` to `"https://github.com/rreminy/FFXIV.WinTitle.git"` and that should make it proceed to next build phase

**Comment by rreminy** [comment]
big oops, fixed now

**Comment by reiichi001** [comment]
Project path should also be `""` since it's flat file structure. 

...hopefully that fixes it! Although if it requires WinForms/WPF, it might still need to go to legacy DalamudPlugins until we can get a Windows runner up and running.

**Comment by rreminy** [comment]
I guess my "." fixed it :D, but if you insist i can change it to ""

**Review by reiichi001 — APPROVED** [review]

**Comment by reiichi001** [comment]
> 

No, that should work too! Build succeeded, so it's mergeable

**Pull request merged**
