### PR TITLE
Mount Radio

### PR DESCRIPTION
**Pull request by Jish2637**
Simple plugin for FF XIV that lets you use a URL radio/live music stream whenever you mount up.

Audio stops when you dismount & will start/connect again when you mount up again.

Radio can also be toggled off/on at any time, mounted or on foot

/radiomount - Open settings

/radiovolume - 1-100 change the volume on the go.

/radiotoggle - toggle radio on/off anytime

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by Jish2637** [comment]
I made a typo in the manifest & have corrected this

**Comment by Felscream** [comment]
I think you can just declare NAudio.Wasapi 2.2.1 as a dependency instead of NAudio if you are only using MediaFoundationReader. It should fix the error related to WinForms.

**Comment by Jish2637** [comment]
> I think you can just declare NAudio.Wasapi 2.2.1 as a dependency instead of NAudio if you are only using MediaFoundationReader. It should fix the error related to WinForms.

thank you very much for that, ill try now

**Comment by Jish2637** [comment]
I have updated this to only use NAudio.Wasapi which has fixed the build error.

**Comment by reiichi001** [comment]
Hi there! I've added this to our review queue. With FFXIV Patch 7.1 maintenance on the horizon, there may be breaking changes to come relatively soon. 

A few notes from code review:
- You should merge https://github.com/Jish2637/MountRadio/blob/master/MountRadio/Plugin.cs#L261 into https://github.com/Jish2637/MountRadio/blob/master/MountRadio/Configuration.cs (this also shouldn't be in the window subsection of your namespace)
- You can probably remove the main window and just use a config window. (You don't need to have both / have them separate. SamplePlugin does this for educational purposes)
- I recommend removing other traces of SamplePlugin, like the goat image and texture fields in your code, as you're not using them.
- I recommend using Dalamud Window helpers for scaled Vector2 sizes, that way your plugin will adjust for font/size scaling.

**Comment by Jish2637** [comment]
> Hi there! I've added this to our review queue. With FFXIV Patch 7.1 maintenance on the horizon, there may be breaking changes to come relatively soon.
> 
> A few notes from code review:
> 
> * You should merge https://github.com/Jish2637/MountRadio/blob/master/MountRadio/Plugin.cs#L261 into https://github.com/Jish2637/MountRadio/blob/master/MountRadio/Configuration.cs (this also shouldn't be in the window subsection of your namespace)
> * You can probably remove the main window and just use a config window. (You don't need to have both / have them separate. SamplePlugin does this for educational purposes)
> * I recommend removing other traces of SamplePlugin, like the goat image and texture fields in your code, as you're not using them.
> * I recommend using Dalamud Window helpers for scaled Vector2 sizes, that way your plugin will adjust for font/size scaling.

Hi reiichi,

Thank you very much for your feedback! I will implement the suggested edits as soon as I can.

**Comment by Jish2637** [comment]
Hi Reiichi,

I believe I have completed the suggested changes & I have put my commit notes in the manifest.

Thanks in advance.

**Comment by Jish2637** [comment]
Hi,

I have tested with Dalamud 11.0.0 and can confirm everything is working as expected.

Thanks in advance.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Testing Results:

Failed to load on linux, not quite sure what the fix is

```
2024-12-07 10:02:46.326 +10:00 [ERR] [LOCALPLUGIN] Error while loading MountRadio, failed to bind and call the plugin constructor
System.AggregateException: Failed to create RadioMountPlugin.RadioMountPlugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: The method or operation is not implemented.
   at NAudio.CoreAudioApi.Interfaces.IAudioEndpointVolume.GetChannelCount(Int32& pnChannelCount)
   at NAudio.CoreAudioApi.AudioEndpointVolumeChannels.get_Count()
   at NAudio.CoreAudioApi.AudioEndpointVolumeChannels..ctor(IAudioEndpointVolume parent)
   at NAudio.CoreAudioApi.AudioEndpointVolume..ctor(IAudioEndpointVolume realEndpointVolume)
   at NAudio.CoreAudioApi.MMDevice.GetAudioEndpointVolume()
   at NAudio.CoreAudioApi.MMDevice.get_AudioEndpointVolume()
   at NAudio.Wave.WasapiOut.set_Volume(Single value)
   at RadioMountPlugin.RadioMountPlugin..ctor() in /work/repo/MountRadio/Plugin.cs:line 41
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, Boolean wrapInTargetInvocationException)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, Boolean wrapInTargetInvocationException)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
--- End of stack trace from previous location ---
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
   --- End of inner exception stack trace ---
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass75_0.<<CreatePluginInstance>g__Create|0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 583
--- End of stack trace from previous location ---
   at Dalamud.Plugin.Internal.Types.LocalPlugin.CreatePluginInstance(LocalPluginManifest manifest, IServiceScope scope, Type type, DalamudPluginInterface dalamudInterface) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 581
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 396
```

**Comment by nathanctech** [comment]
> I will have a go, seems to be NAudio.CoreAudioApi.AudioEndpointVolume relies on features available only on Windows.
> 
> ill look at using cross platform audio lib or implement a platform check to stop the broken feature on Linux.
> 
> could be something like:
> 
> if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) { radioPlayer.Volume = Configuration.Volume; // Windows-specific code } else { Chat.Print("Volume control is not supported on this platform."); }
> 
> public RadioMountPlugin() { if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) { radioPlayer = new WasapiOut(AudioClientShareMode.Shared, 200); radioPlayer.Volume = Configuration.Volume; // Only set on Windows } else { Chat.Print("Volume control is unavailable on this platform."); radioPlayer = new WasapiOut(AudioClientShareMode.Shared, 200); } }

Something even simpler:

https://learn.microsoft.com/en-us/dotnet/api/system.operatingsystem?view=net-8.0, then it's just `OperatingSystem.IsWindows()`, just slightly less typing!

**Comment by reiichi001** [comment]
Pending any further commits for Linux stuff you may want in before the initial merge, this otherwise looks ready to go! I'll plan to merge it tomorrow morning (PST) if I don't hear otherwise.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by reiichi001 — APPROVED** [review]

**Comment by Jish2637** [comment]
thank you very much! My discord handle is josh2367 if you could add me please.

**Pull request merged**
