### PR TITLE
[Testing] Title Roulette 1.0

### PR DESCRIPTION
**Pull request by carvelli**
Similar to using /title (without arguments) in that it picks a random unlocked title - except you can now explicitly configure which titles it should pick from. This selection is saved on a per-character basis.

Picking a random title can be done either using /ptitle or /ptitle groupname.

image

(Thanks to KazWolfe for helping me figure out how to read your character's gender)

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by philpax** [comment]
Just pending testing now before approval! As an aside, you may be interested in [SignatureHelper](https://github.com/goatcorp/Dalamud/discussions/742) to help you keep your signatures nice and clean.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by carvelli** [comment]
Hey, that would be Lizae#4025

**Pull request merged**
