### PR TITLE
[Testing] MonsterLootHunter 1.0.3

### PR DESCRIPTION
**Pull request by danielbrenom**
Submits new plugin for review and testing.
MonsterLootHunter is a plugin for searching materials dropped by world mobs or purchased by NPC vendors directly in-game provided by a simple UI, displaying the requested info and ability to mark the map with the location if available.
The plugin gets the information from the FFXIV Wiki https://ffxiv.consolegameswiki.com/

### CODE REVIEW

**Comment by danielbrenom** [comment]
Could one of the mods point me what is wrong in the manifest that is causing the linter to fail?

**Comment by NotNite** [comment]
To be honest - I have no idea! Don't worry about it too much - we'll see if it's really broken when the plugin gets approved for building (I'm not in power to do that - the TOML looks valid from an eye's glance, though).

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
For those interested, the issue was that there was an invisible character at the start of the manifest (likely a [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)). Removing it fixed the manifest 🙂 

This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by reiichi001** [comment]
Hello!

This plugin has completed plugin review and will be merged into the plugin list shortly.

As a first-time contributor, if you're in the GoatPlace Discord server and would like to get access to the confirmed developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by reiichi001 — APPROVED** [review]

**Comment by danielbrenom** [comment]
Hi, thank you! Yes, I am in the discord server, my handle is danielbrenom#7791
I've only seen this today, since I'm not home at the moment.

**Pull request merged**
