### PR TITLE
Add XIVR

### PR DESCRIPTION
**Pull request by solimproper**
nofranz

### CODE REVIEW

**Review by philpax — DISMISSED** [review]

**Comment by philpax** [comment]
bleatbot, approve

**Comment by solimproper** [comment]
bleatbot, rebuild

**Comment by solimproper** [comment]
bleatbot, rebuild

**Comment by solimproper** [comment]
bleatbot, rebuild

**Comment by BitsOfAByte** [comment]
Quick note to change the plugin icon before merge :)

**Comment by solimproper** [comment]
bleatbot, rebuild

**Review by goaaats — APPROVED** [review]

**Pull request merged**
