### PR TITLE
[Testing] DutyTracker 0.0.0.1

### PR DESCRIPTION
**Pull request by Xpahtalo**
Adding new plugin DutyTracker
Gathers stats like run time and deaths/wipes and prints them to the chat log at the end of the duty.

### CODE REVIEW

**Comment by Xpahtalo** [comment]
Don't accept this version. It's bad. Will fix as soon as possible.

**Comment by MidoriKami** [comment]
Where plogon?
Also, would close https://github.com/goatcorp/suggestions/issues/968

**Comment by Xpahtalo** [comment]
A little bit of life happened, keeping me from doing things. I'm back, now, though.

**Comment by philpax** [comment]
Cool, we'll just need to test it and get one more vote of approval and we'll be good to go

**Comment by Xpahtalo** [comment]
I'm very dumb and had the wrong version. Now it's right.

**Review by philpax — APPROVED** [review]

**Pull request merged**
