### PR TITLE
[Testing] Bartender 1.0

### PR DESCRIPTION
**Pull request by AtaeKurri**
First plugin ever!
Initial release, I hope I did everything correctly for the PR, I'm not used to those kind of things ^^"

This plugin adds a way to store hotbars and load them with a command, a macro or from the GUI.
It has support for automation and gui commands (undo/redo)

This is the "3.0.0" version because I did some testing before and I needed to update the version number, don't mind this ^^"

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Hello! I've added this plugin to our review queue. New plugins may take some additional time to review compared to plugin updates as they go through a more rigorous process. We hope to be in contact soon!

**Comment by reiichi001** [comment]
For the "owners" section in your plugin manifest, please set that to your github username.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
