### PR TITLE
[Testing] WhoAmIAgain v1.0.0.0

### PR DESCRIPTION
**Pull request by MidoriKami**
New plugin for helping you remember who you are.

### CODE REVIEW

**Comment by MidoriKami** [comment]
Link to fill code directly: https://github.com/MidoriKami/WhoAmIAgain/blob/master/WhoAmIAgain/WhoAmIAgain.cs
Yes. It is one file. 26 lines of code.

**Comment by MidoriKami** [comment]
image

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by MidoriKami** [comment]
Just added spacing to the name in the DTR entry from "WhoAmIAgain" to "Who Am I Again?" so it shows up better in `/xlsettings`

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
