### PR TITLE
Glamour spam remover

### PR DESCRIPTION
**Pull request by Shezwick**
I think i did this right. I couldn't find any functionality in existing plugins that accomplish the same thing. I wanted to remove all the chat spam that's generated when you swap to a gearset with a linked glam plate

### CODE REVIEW

**Comment by reiichi001** [comment]
While plugins that duplicate the functionality of other plugins are allowed, TidyChat and NoSoliciting can both hide these types of messages.

TidyChat will hide it by default with an option to enable showing them again.
image

NoSoliciting can filter them using a custom filter by string or regex.
image

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by Shezwick** [comment]
> While plugins that duplicate the functionality of other plugins are allowed, TidyChat and NoSoliciting can both hide these types of messages.
> 
> TidyChat will hide it by default with an option to enable showing them again. image
> 
> NoSoliciting can filter them using a custom filter by string or regex. image

Sorry, I thought I had responded to this. My bad!

I had no idea that this was hidden inside an existing plugin, thanks for the info! I’d like to keep the PR going, as I think theres value in a plugin that does just this. Not a soul that i talked to knew it existed and my various circles are excited to see this implemented

**Comment by Shezwick** [comment]
@reiichi001 Hi, sorry to bother. Just checking if the ball is in my court for the pending-rules-compliance and pending-testing tags. Haven't seen any movement on this in about a week

**Comment by philpax** [comment]
Sorry - ball's entirely in our court, we've got a pretty lengthy backlog as we've been busy. Will try to clear it out soon!

**Comment by Shezwick** [comment]
Not a problem! I figured that might be the case, just wanted to check. Thanks for all the work ya'll do

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Thanks to @herulume for testing! No issues were encountered.
---
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by Shezwick** [comment]
Awesome, thanks! My discord is @shezwick , please add the role when you get the chance!

**Pull request merged**
