### PR TITLE
[Testing] SelfCare v0.1.0

### PR DESCRIPTION
**Pull request by chirpxiv**
Initial build of a plugin idea from goat place's #new-plugin-ideas channel, [see here](https://discord.com/channels/581875019861328007/685275026156683280/1064593316953460787) for the relevant messages. This is a fairly simple plugin that regularly reminds the user to check their posture and drink water.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by reiichi001** [comment]
While testing this plugin, the alarm when off accordingly, but it rendered a tiny black box I could dismiss and spammed the alert sound. After disabling and re-enabling the plugin though, I could reproduce this behavior.

**Comment by chirpxiv** [comment]
> While testing this plugin, the alarm when off accordingly, but it rendered a tiny black box I could dismiss and spammed the alert sound. After disabling and re-enabling the plugin though, I could reproduce this behavior.
> 
> Edit: happened again. (Didn't happen in short tests, is happening on hourly) image

That's odd, I've been using the plugin for the past week or so and never seen this. Were there any errors being logged?

**Comment by chirpxiv** [comment]
I've been able to reproduce this, it's a bug with alerts not being disabled properly. I'll push a fix for this now!

**Comment by chirpxiv** [comment]
@reiichi001 Latest commit should address this issue, please let me know if there's any more problems!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first official plugin! We'll add you to the private channels shortly.

**Comment by chirpxiv** [comment]
Thank you!

**Pull request merged**
