### PR TITLE
Simple Tweaks 1.9.7.0

### PR DESCRIPTION
**Pull request by Caraxi**
***New Tweaks***
- **`Equip items from Hotbars`** - Enables the ability to equip items assigned to hotbars.

- **`Use Collection Command`** - Adds a command to use Collection items. /usecollection *(nebel)*

***Tweak Changes***
- **`Quick Sell Items at Vendors`** - Allowed selling from player inventory while accessing retainer's market inventory.

- **`Set Option Command`** - Added support for cutscene skipping options. *(Gehock)*

***Fixes***
- Should fix crash with `Always Yes` and `Lock Window Positions`

### CODE REVIEW

**Comment by KazWolfe** [comment]
bleatbot, rebuild

**Comment by Caraxi** [comment]
RIP plugin build system

**Comment by Caraxi** [comment]
bleatbot, tell plogon to wake up

**Comment by goaaats** [comment]
bleatbot, rebuild

**Review by goaaats — APPROVED** [review]

**Pull request merged**
