### PR TITLE
[Testing] Casexile 1.0.0.0

### PR DESCRIPTION
**Pull request by RyouBakura**
Hey,

this is just a simple plugin that makes all slash commands case-insensitive.

Repo: https://gitlab.com/Bakura/casexile

### CODE REVIEW

**Comment by MidoriKami** [comment]
This might be better as a SimpleTweak, and wouldn't need to wait several weeks for approval.

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
I agree with Kami - we can run this through the process, but it might take a while, especially given fanfest. You may find it faster / more convenient to go through SimpleTweaks.

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by lmcintyre** [comment]
@RyouBakura Hi! Apologies for the delays in the approval process.

I was curious if you were interested in the Simple Tweaks approach - ST is perfect for small tweaks like this, so I would encourage you to go that route and create a PR to ST _if you're comfortable with that._ There are absolutely no issues with either implementation. We can and will accept your plugin as it is should you decide that.

In order to continue, as ironic as it is, your plugin json's internal name field must match, case-sensitive, the folder you place the manifest in within this repository. Once that issue is resolved, we can continue with plugin approval. Thank you for your submission and your patience.

**Comment by philpax** [comment]
Hi there! We're ready to go ahead with this, but we'd like you to address the issues mentioned by perchbird above _or_ consider submitting this as a Simple Tweak. Let us know what you want to do!

**Comment by MidoriKami** [comment]
The actual error:
```
Build Casexile[testing-live] (d3e861ee47c2cd45eca88ee6b038ba43017c3a9f)
  [17:27:21 INF] Need: Casexile[testing-live] - d3e861ee47c2cd45eca88ee6b038ba43017c3a9f (have nothing)
  [17:27:23 ERR] Could not build
  LibGit2Sharp.NotFoundException: object not found - no match for id (b1426dc715729153fedf5c1bcecab4ef9dfc1327)
     at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
     at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
     at LibGit2Sharp.Core.Proxy.git_submodule_update(SubmoduleHandle submodule, Boolean init, GitSubmoduleUpdateOptions& options) in /_/LibGit2Sharp/Core/Proxy.cs:line 3013
     at LibGit2Sharp.SubmoduleCollection.Update(String name, SubmoduleUpdateOptions options) in /_/LibGit2Sharp/SubmoduleCollection.cs:line 111
     at Plogon.BuildProcessor.ProcessTask(BuildTask task, Boolean commit, String changelog, ISet`1 otherTasks) in /home/runner/work/DalamudPluginsD17/DalamudPluginsD17/Plogon/Plogon/BuildProcessor.cs:line 780
     at Plogon.Program.Main(DirectoryInfo outputFolder, DirectoryInfo manifestFolder, DirectoryInfo workFolder, DirectoryInfo staticFolder, DirectoryInfo artifactFolder, ModeOfOperation mode, FileInfo buildOverridesFile, Boolean ci, Boolean buildAll) in /home/runner/work/DalamudPluginsD17/DalamudPluginsD17/Plogon/Plogon/Program.cs:line 281
```

**Comment by NotNite** [comment]
Anna updated her username on her Gitea instance and the submodule is broken. Change the remote to `https://git.anna.lgbt/anna/XivCommon.git`.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
