### PR TITLE
[Simple Todo] - API 11

### PR DESCRIPTION
**Pull request by Lunalicious**
Update to API 11

This includes literally just the change from 10 to 11 in the plugin's json config and the SDK update :D

Thanks for your work <3

### CODE REVIEW

**Comment by philpax** [comment]
Please update the version of your plugin - happy to merge once that's done 🙂

**Comment by Lunalicious** [comment]
Oooh the fourth number doesn't suffice apparently :D Well, I guess I'll just remove that one then. Sorry for the inconvenience

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
You're only modifying the plugin json manifest, not the csproj where it should be defined. (You don't actually need to set the AssemblyVersion, ApplicableVersion, or DalamudApiLevel in your json. DalamudPackager will take care of filling those in for you!

You'd wanna update the version number here: <https://gitlab.com/moonfox-projects/simpletodo/-/blob/master/SimpleTodo/SimpleTodo.csproj?ref_type=heads#L14>

(Looking at your csproj, you could also trim Author from your json too since you set that in the csproj)

**Comment by Lunalicious** [comment]
I'm terribly sorry for the delay, I had a lot going on recently...
I removed some unneccessary stuff from the JSON but the Author was required to build it.

Thank you for your patience and your help! <3

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
