### PR TITLE
[Testing] Text Hooker 1.0.0.0

### PR DESCRIPTION
**Pull request by aleysos115**
FFXIV Text Hooker will automatically copy the following text to the system clipboard:
- Cutscene / NPC Text
- Battle Text
- Player Chat (All chat sources)
- Item and Action tooltips (Configurable hotkey press required)

The primary purpose of the plugin is to support those wishing to learn languages through playing FFXIV.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Review by aleysos115 — COMMENTED** [review]
Forgot to add project_path into manifest.

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
Looks like you might need to update your deps - I assume that you'll have to make other changes for DT, too

**Comment by philpax** [comment]
Hi there, are you able to update your plugin? It's just a test away from being merged :slightly_smiling_face:

**Comment by philpax** [comment]
Hi, we're going to close this PR for now. Please resubmit it when you have the chance!

**Pull request closed without merging**
