### PR TITLE
[Testing] HotbarHelper v0.0.2.0

### PR DESCRIPTION
**Pull request by kiwikahawai**
Main selling points:

- Searches your hotbars as you use them for missing actions and useful actions like Limit Break
- Particularly useful if you've lost your hotbars or regularly switch between platforms and find actions are missings
- Ability to ignore actions you may have in macros (such as Raise)

I've opted for not supporting CraftActions (DoH) and DoL just yet. I might add Penumbra IPC support for icon fetching while it's in the queue but I'm only anticipating small tweaks rather than large scale changes from this version, unless issues are found.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by kiwikahawai** [comment]
Just an [extremely small change](https://github.com/kiwikahawai/HotbarHelper/compare/d27870521801f0921de5ab4babf2b51e0ab2e4a5...ed6da506f9676bdb511b20774badd69ee0f7d011), I don't know why I left the `slot->Set` in considering the hook'ed function duplicates it (noticed while idly seeing if I could get the better function to work - not yet), and remove a useless debug log message.

**Comment by kiwikahawai** [comment]
Just a [small changeset](https://github.com/kiwikahawai/HotbarHelper/compare/ed6da506f9676bdb511b20774badd69ee0f7d011...aa6936d4c601fdd16270a91eb9a169aeadaec6cb) to fix a couple of small issues I've noticed over the last couple of days (most importantly, 2 omitted disposes), plus add level change checking quickly.

**Comment by kiwikahawai** [comment]
This should be the last change for now.  Now using the hook added to ClientStructs for confirming saves to hotbar slots, instead of the uglier hooked function I had used.

**Comment by kiwikahawai** [comment]
Had loaded a Release build onto another device and noticed that a tab I thought I'd disabled in Release was present (oops), so [this patch](https://github.com/kiwikahawai/HotbarHelper/commit/d2cb8f51725b39827a74f276655a944cdd469133) should fix that and provide a better default window size.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by kiwikahawai** [comment]
Thanks.  It's `@kiwikahawai` like here.

**Pull request merged**
