### PR TITLE
[testing] SimpleMarketBoard 1.0.0.0

### PR DESCRIPTION
**Pull request by Elypha**
Hello, I'm submitting a new plugin.

It's my first time to contribute, so I appreciate it if you would kindly let me know how I can improve!

The plugin currently functions by pulling market data from Universalis.app and show it in game. This process is triggered manually by the user.

It differs from other plugins of its kind in terms of UI design, data presentation and flexibility in user configuration.

I think players who spend a lot of time on in-game trade may find it helpful.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by Elypha** [comment]
> In your `manifest.toml` file, you'll want to ensure the "owner" property has the same casing as your GitHub username.
> 
> I also took a quick look at some of the plugin code. It would be better to fetch world names/IDs using Lumina in your plugin instead of shipping the `World.csv` file from XIVAPI's datamining repository. Those entries are directly extracted from the game as-is.

Thanks a lot for the advice! I have improved the world data part in the code and the `owner` property in the toml. In fact I didn't quite understand what is Lumina when I was coding that part, and I learnt a lot through out the development x

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
Hi there, thank you for the plugin submission! We love to see new plugin authors and will help as required 🙂 

@karashiiro is now in charge of this PR and will try to get it in ASAP. Let us know if you have any questions!

**Review by karashiiro — APPROVED** [review]

**Comment by karashiiro** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
