### PR TITLE
[Testing] Gamba

### PR DESCRIPTION
**Pull request by Comfefe**
A small simple Ui for casino dealers at venues to keep track of their player's bets and and be able to quickly get each player's payout for fast trades.

### CODE REVIEW

**Comment by reiichi001** [comment]
You don't need to remake the PR in its entirety. They can be edited (and moving the manifest to testing, committing that, and pushing it on your previous branch would have updated the PR). I've edited the title and description for you and closed the old one, https://github.com/goatcorp/DalamudPluginsD17/pull/4253.

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
As your github username is `Comfefe`, that's what will need to go into the "owners" part of your manifest.

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
**Testing Results**
Plugin loads and unloads correctly.
Was not in a party so had to play blackjack with a toy chest and wind-up airship
No issues noted

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
