### PR TITLE
MOAction 4.4.0

### PR DESCRIPTION
**Pull request by Infiziert90**
Adoption of this plugin
Thanks goes to the previous maintainer attick, and Alluneve for all the work they recently invested into improving this plugin

**Commands**
- Added 2 new alias /mo and /moaction

**New TargetType**
- Crosshair
  - A static location that acts exactly like "MouseOver"
  - Can be drawn as crosshair onto the screen to give a visualization

**UI Changes**
- Use dalamud window system and ImRaii
- Allow stacks to be reordered
- Renamed the MENU to ALT key 
- Added Searchable action combos
- General cleanup and small improvements to the UI
  - More is planned for the near future
- Added an about tab
  - Support can be reached by using the discord thread button

**Internal Changes**
- Use more of CS for easier maintenance in the future
- Removed a lot of old code that was still lingering around
- Migration code for 4.0 was fully removed
- Improve performance by removing string comparison 

Feedback is always welcome, just drop it in the discord thread or as an issue on github :)

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
