### PR TITLE
[Testing] Chatter Plugin

### PR DESCRIPTION
**Pull request by jlkeesey**

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

In the meantime, I've adjusted the title to fit plugin submission guidelines. 

As for the build error, I think that's related to https://github.com/jlkeesey/ChatterPlugin/blob/main/ChatterPlugin/ChatterPlugin.csproj#L49 because it's adjusting where DalamudPackager's output goes.

**Comment by jlkeesey** [comment]
bleatbot, rebuild

**Comment by jlkeesey** [comment]
bleatbot, rebuild

**Comment by jlkeesey** [comment]
Going to start over, with renaming directory et al. I think things are broken.

**Pull request closed without merging**
