### PR TITLE
[Testing] Umbra

### PR DESCRIPTION
**Pull request by haroldiedema**
Adds a toolbar and world markers.

Full README with screenshots can be found [in the main repository](https://github.com/una-xiv/umbra).

The plugin is separated into 4 projects:

 - Umbra (the plugin itself)
 - Umbra.Common (Framework & Common Utilities)
 - Umbra.Game (Abstraction components that deal with game-related things)
 - Umbra.Interface (UI drawing library)

The [Umbra.Common](https://github.com/una-xiv/umbra/tree/main/Umbra.Common) and [Umbra.Interface](https://github.com/una-xiv/umbra/tree/main/Umbra.Interface) projects come with their own docs (for developers only).

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by haroldiedema** [comment]
@goaaats Please hold off on reviewing this just yet. I'm reworking the drawing library and have to refactor all UI stuff. I managed to improve the performance of layout compositing significantly and simplified the front-facing API.

I'm currently replacing all stuff that uses Umbra.Drawing with Umbra.Interface.

**Comment by haroldiedema** [comment]
Ready 🥳

**Comment by haroldiedema** [comment]
@goaaats The plugin is ready. I'm not adding more features for its initial release and would love to get some initial feedback from people on this.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
Working through plugin testing now that code review's complete. Most things look to be working as expected.

Opening Umbra Settings causes extreme chatbox error log spam, however.
image

**Comment by philpax** [comment]
Also tested by @NotNite, who had the same issue with the chat spam. She also noted that the weather data isn't filled in, and suggested <https://github.com/karashiiro/FFXIVWeather>.

**Comment by philpax** [comment]
This is good to go, we'll let you fix that chatbox error and then we'll merge it in 🙂 

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by haroldiedema** [comment]
> Working through plugin testing now that code review's complete. Most things look to be working as expected.
> 
> Opening Umbra Settings causes extreme chatbox error log spam, however. image

Huh, that is very strange. Are you sure this isn't a build error on your end? There have been quite a lot of people that tested the plugin, but this is the first time I'm seeing this.

**Comment by haroldiedema** [comment]
As for the weather list, please note that the list does not show duplicate entries. For example, if you are in a zone that has the same weather continuously, it is empty by design. The code is based on the linked library as well. Please check in a different (outdoor zone) if it populates there correctly.

**Comment by haroldiedema** [comment]
> please let us know your Discord handle and we'll grant you the role.

I'm already in the Discord server. My handle is `liscion`, name is Una.

**Comment by NotNite** [comment]
For the weather, this is what I saw:

image

For the image missing... I'm not entirely sure? Because shadow.png was copied to the output without issue.

**Comment by haroldiedema** [comment]
Wow, that is really weird. It seems like it is completely crashing in the Empyreum 😨 Let me see if I can reproduce this.

**Comment by NotNite** [comment]
Oh, hm, probably just an issue with the icon missing so it didn't update. I wonder why it's not copying in our CI...

**Comment by haroldiedema** [comment]
Hmm, does the icon get special treatment in the CI maybe? It's included in the .csproj file just like the shadow.png and plugin json file:

```xml
    <ItemGroup>
        <Content Include="Umbra.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="images\icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="images\shadow.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
```

But yeah, It does sound plausible that it crashes somewhere halfway due to the missing image, causing other parts of the plugin to fail.

**Comment by philpax** [comment]
Nice! We'll just quickly retest that, and if it's all working, we'll merge 🙂 

@kelvin124124 also had some additional feedback that I just saw now. None of this is blocking, but you may find it useful:

> AI summarised for clarity. 
> Using 4293c97 on GitHub. (a day ago)
> Pros:
> 
> - The plugin generally performs as advertised, especially appreciating the built-in gear set switcher.
> - No major bugs have been encountered on the toolbar functionality.
> 
> Feature Requests:
> 
> - A semi-transparent and click-through  toolbar in vanilla UI editing mode.
> - Adjustable UI size for better customization.
> - Implementation of anti-aliasing or high resolution text and asset display.
> - A persistent toolbar that doesn't disappear when teleporting, for a more consistent visual experience.
> 
> Issues:
> 
> - The Eureka coffer function fails to work, possibly due to game language modifications (Chinese).
> - Suggestion to hook actual functions directly instead of relying on chat messages for enhanced functionality, though acknowledged as a lower priority.
> - The toolbar's UI elements (toolbar and markers) overlap (penetrate) when placed at the top of the screen.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Good to go! (Thanks to @NotNite for retesting)

---

Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by haroldiedema** [comment]
Thanks a lot guys, and @kelvin124124 for the great suggestions! I'll add them as FR issues to the repo to keep track of them 😄

**Pull request merged**
