### PR TITLE
Added ItemVendorLocation

### PR DESCRIPTION
**Pull request by electr0sheep**
First time contributing to new plugin repo, hoping I did everything right.

### CODE REVIEW

**Comment by philpax** [comment]
Manual diff: https://github.com/electr0sheep/ItemVendorLocation/compare/6628b161d69f99bac7a37debf2659df279a66e9a..b82d028acae43250fa6ca8e415ce045b33a3da7c

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Ah, looks like you got bit by Linux case sensitivity - can you rename the JSON to `ItemVendorLocation.json`? You should be able to use `git mv` for this: https://stackoverflow.com/a/20907647

**Comment by electr0sheep** [comment]
> Ah, looks like you got bit by Linux case sensitivity - can you rename the JSON to `ItemVendorLocation.json`? You should be able to use `git mv` for this: https://stackoverflow.com/a/20907647

Done...I'm pretty sure

**Comment by philpax** [comment]
You'll need to update the commit in the manifest here.

**Comment by electr0sheep** [comment]
> You'll need to update the commit in the manifest here.

Oh right I totally forgot 😅

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congrats on your first DIP17 submission 🎉

**Comment by electr0sheep** [comment]
Thanks! I believe it was you who came up with this new system, and I think it's vastly improved over the old way. Thanks for all that work!

**Pull request merged**
