### PR TITLE
[Testing] Add MemoryMarker

### PR DESCRIPTION
**Pull request by MidoriKami**
New Plugin "MemoryMarker"

A simple Waymark Management plugin with no configuration.
Automatically saves and loads waymarks when entering and leaving zones, so you get 30 waymarks per-zone.
Allows you to edit how the waymarks display in the Waymarks menu.

If WaymarkPreset is installed, the auto-load feature will automatically be disabled.

image

### CODE REVIEW

**Comment by MidoriKami** [comment]
Notes to reviewers: 

This plugin does not have any form of editor.
Users are not able to import or export waymarks.
Only waymarks that were saved via normal means are loaded.

If Waymark Preset is detected, then waymarks are not written to memory.

Here are some clips to see it in action:

https://user-images.githubusercontent.com/9083275/213725432-2aebdf4e-b8be-4c00-b735-62f7c73fae23.mp4

https://user-images.githubusercontent.com/9083275/213725914-b8e83d80-2e1c-4fb4-a2ba-8fcdf2725873.mp4

**Comment by MidoriKami** [comment]
The behavior of the plugin has been modified, the descriptions above have been edited, if you read them before the edit, I encourage you to take a look again. The new behavior plays well with Waymark Preset.

**Comment by MidoriKami** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Review by philpax — APPROVED** [review]
you're not content with the PR count trophy, you've gotta swing for the plugin count trophy

**Comment by MidoriKami** [comment]
> you're not content with the PR count trophy, you've gotta swing for the plugin count trophy

Oh there's a trophy for that? Well I better get to work.

**Pull request merged**
