### PR TITLE
[Testing] HUDUnlimited

### PR DESCRIPTION
**Pull request by MidoriKami**
HUDUnlimited is a new plugin that gives you *complete* control over your user interface.

This plugin allows you to modify any and all UI elements to be exactly how you want.

Supports the ability to import and export presets.

image

### CODE REVIEW

**Comment by MidoriKami** [comment]
Useful preset for testing, to demonstrate basic functionality easily.
```
H4sIAAAAAAAACnWOQUvEMBCF/0qYXhSKW1Gs5laLggdrYYvuuizL7CbWQNpIkopL6X93Git4sJc3w3vfPGbTQ2GELNG/A4ddhbaW/qF9Mzk6f4t2cQlxIAps5AzBTti479Gy7OCVaVklvzw7jaKZvrxz3jRT4z+nhDx9SmuVkHct7rUUwL3tZAylcWrEgPewAn5xE8MaeDrEsDygprpgJ2fXwadJSW60sVNyHnzS16AvpERkQvyFkp/jACUUP3baqw99nC0i5lk5RY/+/nmvsXbAr9Jh+w1o1LHOYgEAAA==
```
This moves the cast action text below the cast bar, and scales it down to 80%
image

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by MidoriKami** [comment]
Is there something preventing this plugin from receiving a code review? All things considered, this plugin is relatively simple in how it functions, a majority of the code is ImGui UI Code.

**Comment by philpax** [comment]
Hi - sorry, no, there's no hold-up. We generally code review plugins after we get approval consensus; the exceptions to this have been for very straightforward plugins where the code review can be done in a few minutes.

We're close to reaching consensus on this; we're just confirming amongst ourselves that exposing full UI control won't pose any issues. I think we'll have an update for you soon.

**Comment by MidoriKami** [comment]
If I helps I have plans to include some documentation on some of the hazards of ui manipulation, most namely, if you move an element outside its containing collision node, it will no longer react to input events.

As well as including some instructions on how to restore the UI to original state if you didn't like your modifications.

Disabling the plugin and relaunching the game will **always** undo **any** modifications made. All modifications are made in runtime, if an option is disabled and the associated addon is reloaded, it will reflect the vanilla state of the element immediately.

**Comment by philpax** [comment]
Thanks, that does help! Knowing that it'll reset gracefully is very useful. I wouldn't worry about putting the documentation in until approval's done, but it shouldn't be too far off with your additional clarification 🙂

**Comment by heyyitsdaniel** [comment]
Any updates on this? I was really looking forward to it :(

**Comment by philpax** [comment]
Hi there! No news yet, unfortunately - it's still in the pipeline, there will hopefully be some movement on it soon 🙂

**Comment by Clueless-AI** [comment]
Hello,
Is this project abandoned since Kami is taking a break or left forever ? I just cameback to the game and saw that.

**Comment by MidoriKami** [comment]
> Hello, Is this project abandoned since Kami is taking a break or left forever ? I just cameback to the game and saw that.

This project is not abandoned, this project is considered complete. It functions entirely as intended and has need no further modification since I submitted it for review to be added to the dalamud main plugin repository.

It's simply waiting for someone to take the time to review the code and test it on the Approval Committee's side.

**Comment by Clueless-AI** [comment]
> > Hello, Is this project abandoned since Kami is taking a break or left forever ? I just cameback to the game and saw that.
> 
> This project is not abandoned, this project is considered complete. It functions entirely as intended and has needed no further modifications.
> 
> I am not actively playing FFXIV currently, however, all my plugins were designed to require minimal effort to update.
> 
> It's simply waiting for someone to take the time to review the code and test it on the Approval Committee's side.

That's good to know, I thought you were gone for real. Hope everything is well on your side.

Let's hope someone gets it approved, so this piece of art can be tested by the players :D

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by MidoriKami** [comment]
bleatbot, rebuild

**Comment by Clueless-AI** [comment]
Hello,
I don't really understand much in the few recent updated on this thread, just wanted to know if tthe plugin is out for testing or not yet since it says on tthe last comment that the testing is live but when I try to add the repo in game it's not working.

thanks in advance

**Comment by reiichi001** [comment]
It's happening

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
