### PR TITLE
[Testing] First release of HimbeertoniRaidTool v0.5.1.31

### PR DESCRIPTION
**Pull request by Koenari**
A tool mostly aimed at savage raiders to help have an overview of current gear of your static and help you make decisions of how to distribute gear. Aditionally a way to keep track of your personal and groups BiS gear and melds, including calculations of your stats (similar to etro or the Balance spreadsheets)

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by Koenari** [comment]
If applicable please prioritize the smaller new plugins coming after this. I don't wanna hold up the process for them as this is already available to people
Note: This does not mean I don't care when to publish oficially and retire my repo, just that the people using it now already get updates from my repo and other plugins in the revie queue might not have taht luxury)

**Comment by philpax** [comment]
Happy to do that. With this, we're blocked on deciding if it meets our combat guidelines - can you record a video of the plugin in use to help us with that?

**Comment by Koenari** [comment]
While I do not want to add more work. I found it best practice to finalize some internal reworks that would lead to beside other things migrating configuration and data before people start using the plugin. Additionally I do not want to carry a ton of legacy code and support to live/stable

**Review by philpax — APPROVED** [review]

**Pull request merged**
