### PR TITLE
[Testing] MiniMappingway - Fixed 3 bugs

### PR DESCRIPTION
**Pull request by jaycewhite**
Bug fixes: fixed player markers displaying (very) incorrectly. Fixed marker stuttering if minimap was unlocked. Fixed possible marker flicker issue

### CODE REVIEW

**Comment by philpax** [comment]
Hm, looks good to me, but did you want to leave that verbose log in?

**Comment by jaycewhite** [comment]
No I definitely do not, thanks! 😅

**Comment by jaycewhite** [comment]
I'm confused, what did I break? Here is the commit https://github.com/jaycewhite/MiniMappingway/commit/97c117aa868aa911d8e1ed53e246603814c89f67

**Comment by philpax** [comment]
bleatbot, rebuild

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
weird

**Pull request merged**
