### PR TITLE
Add Eorzea Votes 1.0.6

### PR DESCRIPTION
**Pull request by lojewalo**
Vote on opinion polls. See the result. Break the results down by volunteered demographics.

### CODE REVIEW

**Comment by lojewalo** [comment]
If this is going to be merged somewhat soon, could I get a ping on Discord from PAC so I can reset the server database? Thanks.

**Comment by lojewalo** [comment]
Whoops, flash update since I forgot to actually take into account certain privacy settings.

**Review by lojewalo — COMMENTED** [review]
lgtm :smiling_face_with_tear:

**Comment by reiichi001** [comment]
Plugin testing passes as of 24dfc9d. Any new builds on the PR will involve a new round of testing.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
All reviewed. Apologies for the wait - backlog clearing took a while.

I know you mentioned you wanted to wipe the database before this went live, so I'm holding off on the merge.

Just let us know when to hit the button!

**Comment by lojewalo** [comment]
All set, thanks.

**Pull request merged**
