### PR TITLE
[Testing] xivr 0.0.5.3

### PR DESCRIPTION
**Pull request by ProjectMimer**
Too many changes

### CODE REVIEW

**Comment by ProjectMimer** [comment]
bleatbot, rebuild

**Comment by lmcintyre** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
Hi there, it looks like the build is misconfigured:
```
   [18:06:23 INF] /work/repo/xivr/Structures/ffxivRenderTargetManager.cs(27,16): error CS0246: The type or namespace name 'Notifier' could not be found (are you missing a using directive or an assembly reference?) [/work/repo/xivr/xivr.csproj]
  [18:06:23 INF] /work/repo/xivr/xivr.cs(37,39): error CS0122: 'Framework' is inaccessible due to its protection level [/work/repo/xivr/xivr.csproj]
  [18:06:23 INF] /work/repo/xivr/xivr.cs(38,39): error CS0122: 'ClientState' is inaccessible due to its protection level [/work/repo/xivr/xivr.csproj]
  [18:06:23 INF] /work/repo/xivr/xivr.cs(39,39): error CS0122: 'TitleScreenMenu' is inaccessible due to its protection level [/work/repo/xivr/xivr.csproj]
  [18:06:23 INF] /work/repo/xivr/xivr.cs(40,39): error CS0122: 'Condition' is inaccessible due to its protection level [/work/repo/xivr/xivr.csproj]
  [18:06:23 INF] /work/repo/xivr/xivr.cs(42,
  [18:06:23 INF] 39): error CS0122: 'ChatGui' is inaccessible due to its protection level [/work/repo/xivr/xivr.csproj]
```

Is this something you can fix?

**Comment by ProjectMimer** [comment]
thanks for looking in to this.
i had a quick look and fixed the errors but couldnt get it to initialize in vr.
at the moment were looking into getting openxr working and once thats done move everything accross

**Comment by philpax** [comment]
Awesome, good luck! I know OpenXR can be quite a hassle, but I hope you'll be able to get to the bottom of it 🙂

**Comment by philpax** [comment]
I'll close this for now - looking forward to the OpenXR integration 🙂

**Pull request closed without merging**
