### PR TITLE
Add PingPlugin and SoundSetter

### PR DESCRIPTION
**Pull request by karashiiro**
Expecting CI failures, will feex

### CODE REVIEW

**Comment by karashiiro** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Given TTT will be broken until we figure out how to tackle Windows builds, maybe remove it from this PR?

**Comment by karashiiro** [comment]
I'm working on it, I use Windows Forms for file dialogs and NAudio for sound. I'm replacing the Windows Forms dialogs with imgui ones, and the .NET 6 version of NAudio doesn't necessarily require the Windows platform target. The platform-agnostic version of NAudio doesn't have the sound file interface I was using, but I might be able to get it working with a different sound file interface.

**Comment by karashiiro** [comment]
k nevermind

**Review by philpax — APPROVED** [review]

**Pull request merged**
