### PR TITLE
Pet Scale 1.2.1.1

### PR DESCRIPTION
**Pull request by Kurochi51**
nofranz
Just replaced my own fixed width icon font with the dalamud provided one

### CODE REVIEW

**Comment by Kurochi51** [comment]
huh, I could have sworn this was in stable already

**Comment by Kurochi51** [comment]
bleatbot, rebuild

**Comment by Kurochi51** [comment]
bleabot, rebuild

**Comment by Kurochi51** [comment]
bleatbot, rebuild

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
