### PR TITLE
[Testing] Acquired Date 0.1.0.0

### PR DESCRIPTION
**Pull request by Glyceri**
**Initial commit of Acquired Date!**

**This plugin tracks and shows you the date you acquired/got the following:**
  - Achievements
  - Quests
  - Duties
  - Levels (For any Job)
  - Fish
  - Sightseeing Log Entries
  - Glasses
  - Minions
  - Mouts
  - Orchestrion Rolls
  - Fashion Accessories
  And more!

**Using the lodestone you can import a backlog of the following dates:**
  - Achievements
  - Quests
  - Glasses
  - Minions
  - Mounts

_Expect a UI rework and more ways of importing data soon after release!_

### CODE REVIEW

**Comment by reiichi001** [comment]
I've added this plugin to our review sheet

**Comment by philpax** [comment]
That's quite extensive! I wasn't expecting it to be so much code and so many hooks O_O

I assume you've taken all of the necessary measures to ensure that there aren't any problems with hitting Lodestone too often; I noticed the 1.5s timeout but I'm not sure if anything else is necessary. I'd be curious to hear what you think / what your experience has been.

**Comment by Critical-Impact** [comment]
AcquisitionDate
 - Plugin loads/unloads correctly
 - Plugin functionality works, was able to download achievement data

**Comment by Glyceri** [comment]
> That's quite extensive! I wasn't expecting it to be so much code and so many hooks O_O
> 
> I assume you've taken all of the necessary measures to ensure that there aren't any problems with hitting Lodestone too often; I noticed the 1.5s timeout but I'm not sure if anything else is necessary. I'd be curious to hear what you think / what your experience has been.

I have been running a lot of lodestone tests and read code from all the scrapers. I made sure that upon basically any error the whole request gets cancelled and too many requests send to the lodestone basically counts as an error. I am not sure if 1.5s is enough time, the real lodestone limit is 0.99 seconds per request so I went above that. Real world testing (aka, first week of testing release) will show if 1.5 seconds is good, I don't feel comfortable ever going below it!

I have also tested many scenarios like trying to scrape other users or invalidating a token midway through a request. All of these result in the lodestone cleanly refusing to give any data any my plogon will then cancel the requests.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on another plugin added to the main Dalamud plugin repository!

As a multiple-time contributor, you get a thumbs up. Keep it up!

**Pull request merged**
