### PR TITLE
DailyDuty v5.2.0.3

### PR DESCRIPTION
**Pull request by MidoriKami**
Remove Teleporter Plugin dependency.
Fix Raids Modules not updating to new duties.
Fix Jumbo Cactpot time calculation.
Fix plugin opening config window on load.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
@goaaats looks like this one will need your intervention as well

**Comment by MidoriKami** [comment]
DailyDuty, NoTankYou, and CurrencyAlert, all use the same combination of KamiLib, KamiToolkit, and main plugin code. It's very odd to me that it works sometimes, but not others.

I won't really have any time until this upcoming to mess with things, so ideally by then we can work something out.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
