### PR TITLE
[Testing] Fungah

### PR DESCRIPTION
**Pull request by imaginary-png**
Just draws a lil dot on the south safe spot during Any Way the Wind Blows, to make it easier to see during big crowds.
image1
image2

### CODE REVIEW

**Comment by imaginary-png** [comment]
bleatbot, rebuild

**Comment by imaginary-png** [comment]
:(

**Comment by imaginary-png** [comment]
bleatbot, rebuild

**Comment by imaginary-png** [comment]
it is? isn't it?

**Comment by Infiziert90** [comment]
Your internal plugin name is still "Sample Plugin" and I believe Dp17 uses that one for paths

**Comment by imaginary-png** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by Infiziert90** [comment]
Tested your plugin for the PAC as v0.0.0.1 and noticed some smaller issues/slight annoyances for myself at least.

+ The point isn't static, it moves quite a bit
+ The point is always there, you just have to be close enough to the arena for it to be triggered

Both of them combined makes it a bit distracting and maybe also misleading as other games are played in the same arena.
So making it only appear while duty bound with the current duty / entered duty being the specific game would help a lot.

**Pull request merged**
