### PR TITLE
[Testing] FFXIV RP Event Calendar (Initial Version)

### PR DESCRIPTION
**Pull request by erroch**
Initial  version of the plugin for the ffxiv rp event calendar.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Hello!

Our build system will require specifying full git path to pull source. In this case, adjust your manifest.toml to use `https://github.com/erroch/FFXIVRPEventCalendarPlugin.git` and that should get it going.

I've added this plugin to our reviewers' queue and we hope to get back to you soon!

**Comment by erroch** [comment]
Thanks, reiichi001.  url updated as requested.

**Review by erroch — COMMENTED** [review]
Updating commit to version with fixed manifest file and internal name.

**Comment by MidoriKami** [comment]
The title of this pr should start with `[Testing]` to make sure that merge notifications are sent to the correct channel.

**Comment by erroch** [comment]
> The title of this pr should start with `[Testing]` to make sure that merge notifications are sent to the correct channel.

Corrected as requested, thanks.

**Comment by reiichi001** [comment]
Hello! Initial load and basic test looks good. There is a minor issue for first load where the plugin window's columns are squished. 
image

This is an imgui quirk and should be fixable with some default values (it looks like the plugin handles scaling fine for the most part).

Aside from that, I noticed that the Categories options don't wrap and if a user resizes the window in certain layouts, they can clip the options, but that's not a blocking issue. 
image

**Comment by erroch** [comment]
> edit: I'm not sure what the `/eventsnow` and `/eventsnext` commands do. I didn't notice a change in the plugin UI or output in the chatbox. Is there an example or sample for these?

Fixed the default sizing issue,  thanks for catching that.   
The categories should (hopefully) now wrap to new lines properly.
I removed the command hooks for /eventsnow and /eventsnext.   They were left over from early testing and I forgot to remove the command manager handler entries when removing their functionality.

**Comment by reiichi001** [comment]
Awesome! Allow me to congratulate you on your first plugin on the main repo!

Users who are opted into plugin testing will be able to get it today once their plugin installer lists refresh. After some time (or if no user reported bugs), feel free to bring it over to stable!

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
