### PR TITLE
[Testing] XIVWindowResizer v1.0.0.0

### PR DESCRIPTION
**Pull request by AlexCSDev**
This plugin adds command which allows to resize FFXIV window to arbitrary size/resolution. This is primarily intentended to be used to take screenshots in higher resolutions than display resolution without using DSR and other supersampling technologies because those usually require you to switch to fullscreen mode and that might be very annoying when you are using external applications like Anamnesis.

Since this is quite simple plugin and similar functionality (just implemented a bit differently) has been used in XIVR for quite a while now, I don't think there is any need to push it to testing first.

### CODE REVIEW

**Comment by reiichi001** [comment]
All new plugins should be pushed to testing first, even if they're using slices of other plugins. After a testing period of a few days, it can then be moved to stable.

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by AlexCSDev** [comment]
Alright, I assumed that this is not strict requirement based on what I've read in docs, moved into testing.

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!
 
As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by AlexCSDev** [comment]
Thank you, my discord handle is: Alexsey#9211

**Pull request merged**
