### PR TITLE
[Testing] ShopItemRevealer 1.0.0.0

### PR DESCRIPTION
**Pull request by nathanctech**
New plugin that pops a window on supported vendors (currently only beast tribes) showing items the player doesn't have access to and are hidden from the shop, along with a reason why.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Hi, it looks like your repository isn't accessible to the public?

**Comment by nathanctech** [comment]
My bad! I totally forgot to swap it to public...

**Comment by nathanctech** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Shop Item Revealer
 - Plugin loads/unloads correctly
 - Hitting the Open button within the config window logs an error "NPC not found in shop list.". Normally this button is supposed to open a window and it might be confusing to users
 - Plugin works otherwise for supported npcs

**Comment by nathanctech** [comment]
Thanks for reviewing. I could either make it display a message to the chat saying there's no NPC to open the window for, or show the last NPC's stock. If it's no issue until release into testing I'll adjust the behavior then!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by nathanctech** [comment]
Thanks! It's `_.era._` with the underscores.

**Pull request merged**
