### PR TITLE
[Testing] Doorbell v0.1

### PR DESCRIPTION
**Pull request by SoyaX**
New plugin.
Will play a simple (customizable) chime when another player enters or leaves the current house.

image

### CODE REVIEW

**Comment by SoyaX** [comment]
did I break something?

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!
 
As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by SoyaX** [comment]
Thank you, my discord username is Soya#3245

**Pull request merged**
