### PR TITLE
feat. FFXIVRPEventCalendarPlugin update to 2023.08.09 version. (fixed icon image, added add/report event links)

### PR DESCRIPTION
**Pull request by erroch**
feat. FFXIVRPEventCalendarPlugin update to 2023.08.09 version. (fixed icon image, added add/report event links)

### CODE REVIEW

**Comment by erroch** [comment]
Well, looked like it git grabbed all the commits from my initial version as well, my apologies.  last commit is the only new one.

**Comment by reiichi001** [comment]
The commits are due to <https://github.com/erroch/DalamudPluginsD17/tree/main>'s current status. 

What some devs do is not fork/maintain a fork of DalamudPluginsD17 and in turn just use the web editor, let it make a one-time fork/branch, and delete it after. Otherwise, I'd recommend fast-forwarding your local main to D17's main, make a branch, and PR from that branch. (And then for future updates, swap back to main, fast-forward, re-branch, etc).

Our build system might be mad at that manifest. Multiline strings use triple quotes, so it doesn't know what to do. 
ex: `Tomlyn.TomlException: (6,14) : error : Invalid newline in a string`

This should work:
```toml
[plugin]
repository = "https://github.com/erroch/FFXIVRPEventCalendarPlugin.git"
commit = "68e4e1fda875fcf511d906f92ee2ffffe8cbd2ed"
commit = "5983f812d15b2c3b01e43c1c7c6cf4661f315e53"
owners = ["erroch"]
project_path = "FFXIVRPEventCalendarPlugin"
changelog = "Initial Version"
changelog = """
2023.08.09
- Fixed improper icon.
- Added 'add event' and 'report event' links.
"""
```

**Comment by erroch** [comment]
Thanks, reiichi001,  want me to abandon this, and restart, or just remember that for next time and fix the manifest?

**Comment by reiichi001** [comment]
You can just fix the manifest! We see commit stuff like this often and it doesn't actually hurt anything.

**Comment by reiichi001** [comment]
Changes and icon look good. Version will need to be bumped per release. I can then merge it in.

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
