### PR TITLE
[Testing] Tick Tracker 0.0.0.2

### PR DESCRIPTION
**Pull request by Kurochi51**
Mostly repurposed an abandoned plugin, [MPTimer](https://github.com/talimity/MPTimer), although now it can keep track of HP and MP, and is mindful of stuff like Lucid Dreaming and HP Regen statuses.

I don't know if I set up the project properly, so please let me know if there's any issues.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by Kurochi51** [comment]
My discord handle is `@.kurochi`

**Pull request merged**
