### PR TITLE
[Testing] WhichMount 1.0.0.0

### PR DESCRIPTION
**Pull request by megurte**
Dalamud Plugin that shows information about player's mounts and it's acquisition methods.
Has few more modifications to get more concrete information about other player's mount.

The plugin has a configuration that is controlled by the Dalamud QL XIV environment.

Type /mountsconfig in the in-game chat command to open the configuration window or use the main Dalamud plugin window with the Settings button.

Available options:

- Mount ID: Shows game data mount id.
- Show Obtainable: Indicates whether it is currently possible to obtain this mount in the game.
- Show Number of Seats: Displays the number of people that can ride the mount.
- Has unique actions: Shows if mount has uniq actions or not.
- Has unique BGM: Shows if mount has own music or not.

The code uses data from the [FFXIV wiki](https://ffxiv.consolegameswiki.com/wiki/FF14_Wiki) to get detailed information about the searched mount.

UPD
Now uses local csv to fetch data, not web requests

### CODE REVIEW

**Comment by MidoriKami** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by philpax** [comment]
Looks like you have a reference to DalamudInjector in your project file? That probably shouldn't be there

**Comment by reiichi001** [comment]
Code review comments:
- Please don't try to merge your plugin manifest and a custom plugin repository. While these have overlap on many fields, they are not the same things and you should keep them as separate files. (All download links, API level, IconUrl, and AssemblyVersion entries should be removed as DalamudPackager and our build system will handle those.)
- References to DalamudInjector should be removed. Nothing is using them and that DLL and the path you've set for it is local to your machine and cannot be resolved in the build system.
- I would highly recommend that instead of parsing `https://ffxiv.consolegameswiki.com/wiki/Mounts`, you save the table you're scraping from ConsoleGamesWiki as a CSV or other tabular format to load into the plugin, as your plugin will fail in horrible ways if the user's machine fails to load the page (ex: connection issues to the site, the site is down, etc) or if the structure of the wiki page ever changes, which it has high likelihood to do. 
- The https://github.com/Critical-Impact/LuminaSupplemental library and https://github.com/foophoof/CollectorsAnxiety plugin may offer some guidance on how to get some of this information from the game directly, like number of seats, how to unlock it, and which patch it came from. https://github.com/foophoof/CollectorsAnxiety/blob/main/CollectorsAnxiety/Data/Unlockables/Mount.cs and https://github.com/foophoof/CollectorsAnxiety/blob/main/CollectorsAnxiety/Game/UnlockItemCache.cs

**Comment by megurte** [comment]
Fixed stuff from code review:

- Manifest and custom plugin json now separated
- Removed local ref to custom lib, now it's submodule. Also removed web request lib ref
- Data fetch moved to local resources from web request
- Added few more options to display

**Comment by megurte** [comment]
Is there anything else I need to do to test my plugin or it's just in queue?

**Comment by reiichi001** [comment]
No actions needed on your end currently! It's still going through the review process.

**Comment by MKhayle** [comment]
Hi! I tested your plugin, and there are my observations:

- Loads correctly in french
- Lacks a main UI callback but that's by design
- Works, but is a bit lackluster in how data ("Has uniqueMusic") is presented, and also displays incorrect information (mount availability always returns "No")
- Some mounts like Cerberus, EX mounts, and every event or mog station mount have no info about how to acquire them 
- Some mounts like Ty'aitya which are to be purchased have a flag which gets cut off after the comma I guess

```[03:30:58] <Someone>'s mount: Ty'aitya
[03:30:58] Acquired by: Purchased from Edelina in Mor Dhona (x22
[03:30:58] Mount ID: 342
[03:30:58] Number of seats: 1
[03:30:58] Has actions: Yes
[03:30:58] Has uniqueMusic: No
[03:30:58] Is currently obtainable: No
[03:30:58] ===================
[03:32:02] <Someone>'s mount: Mégashiba
[03:32:02] Acquired by: Information not found
[03:32:02] Mount ID: 294
[03:32:02] Number of seats: 1
[03:32:02] Has actions: Yes
[03:32:02] Has uniqueMusic: No
[03:32:02] Is currently obtainable: No
[03:30:58] ===================
[03:34:43] <Someone>'s mount: Garlond GL-IIT
[03:34:43] Acquired by: Purchased from Horrendous Hoarder in Unnamed Island (12.6
[03:34:43] Mount ID: 335
[03:34:43] Number of seats: 2
[03:34:43] Has actions: No
[03:34:43] Has uniqueMusic: No
[03:34:43] Is currently obtainable: No
```

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Thanks for testing! That's sufficient to pass this initial stage, but I'd recommend updating as soon as possible to resolve the issues.

---
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by megurte** [comment]
Thank you! Yes, i already see the problems and the reasons for their appearance, so i will fix it today or around
My nickname in dalamud's discord server is `megurt`

**Pull request merged**
