### PR TITLE
Next batch of Anna plugins

### PR DESCRIPTION
**Pull request by ascclemens**

### CODE REVIEW

**Comment by ascclemens** [comment]
You need to quote the paths you pass to that script.

**Comment by goaaats** [comment]
I'll have a look later

**Comment by goaaats** [comment]
@ascclemens TOML object for TextBoxStyler is "plugins", not plugin: https://github.com/goatcorp/DalamudPluginsD17/pull/103/files#diff-984f453f3b97063e26d9dc05827338d0450955a55f7e8b9f43a58ee10698a5c4R1
This should fail lint-manifest but I guess QuestMap took care of that

**Comment by goaaats** [comment]
image
Works as expected now

**Comment by ascclemens** [comment]
bleatbot, rebuild

**Review by goaaats — APPROVED** [review]

**Pull request merged**
