### PR TITLE
[Testing] CopyTranslated 1.0.0

### PR DESCRIPTION
**Pull request by kelvin124124**
The plugin allows users to copy translated in-game item names with a single click from the context menu.

### CODE REVIEW

**Comment by lmcintyre** [comment]
bleatbot, approve

**Comment by lmcintyre** [comment]
@kelvin124124 Hi! Thanks for your plugin submission. Some changes for you:
- On [this line](https://github.com/kelvin124124/CopyTranslated/blob/ecf77eb7de2b996fe0b74d77b6ebd2bbda7aa521/CopyTranslated/Plugin.cs#L31) your plugin's "Name" field is "Item Translator Plugin". I'll be honest and say I'm not sure where this is used over the "Name" field from the plugin json, but I would recommend you align them to be the same thing.
- Your plugin's "InternalName" must match the folder you place it within in this repository, case sensitive. Your "copy" is lowercase
- The author field in the manifest in this repository must match your GitHub username

**Comment by kelvin124124** [comment]
@lmcintyre Thank you. I fixed the listed issues.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by kelvin124124** [comment]
@philpax Thank you. My Discord user ID is 778981397729509387 :D

**Pull request merged**
