### PR TITLE
[Testing] Mounting Party v1.0.0.0

### PR DESCRIPTION
**Pull request by meoiswa**
This simple plugin overrides Mount Roulette to spawn a randomly picked multi-seater mount the user has unlocked, whenever they are in a Party

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
@tommadness has tested this and has noted that it conflicts with Better Mount Roulette. Is there a reason why you've created a new plugin instead of contributing to BMR? If so, is that something we can help with? The two plugins overlap significantly, so we'd like to reduce the amount of duplication if possible.

**Comment by meoiswa** [comment]
No reason in particular, I just didn't feel it was quite the same functionality, as BMR is a lot more customizable.
If you guys think it should be a feature of BMR i can just make it a PR

**Comment by CMDRNuffin** [comment]
I am currently in the middle of a major refactoring (including migrating to per-character config), so it would probably make sense to do that after (in a way that maybe doesn't _totally_ obsolete this plugin, maybe via ipc?), and in the meantime just have a warning that these plugins don't currently work together. Or put this on hold altogether.

**Comment by philpax** [comment]
Our preference would be as part of BMR and/or to make this functionality easily accessible through BMR, so that people who want the simple experience can get there quickly. If you would prefer to keep it as a separate plugin, that's fine, but it does mean that you'll have to deal with BMR interop problems.

**Comment by meoiswa** [comment]
As suggested, I've turned this plugin into a feature of BMR, currently PR'd [here](https://github.com/CMDRNuffin/BetterMountRoulette/pull/9)

**Pull request closed without merging**
