### PR TITLE
DailyDuty v4.0.0.3

### PR DESCRIPTION
**Pull request by MidoriKami**
**New Configuration System**
All modules now store both a `.config.json` and a `.data.json` file in the DailyDuty configuration folder.
You can now copy just the `.config.json` files between characters to easily sync the config options.
*Due to using a completely new system, you'll get new default configs, you can safely remove the old configs manually if you wish*

**Simplified UI Design**
All modules now display configuration and data in the exact same way as each other for a nice consistent layout.

**New Notification Options**
You can now set the notification channel (Party, FC, Alliance, etc) **per** module.
You can also set your own custom notification messages.
Added new "Reset Notification" option that will notify you that a reset recently occurred during your game session.

**Module Data Display**
Modules now display **all** relevant data in the data tab, if you have bugs or issues, please be sure to attach a screenshot of the data tab for the relevant module.

**New Module Features**
There have been several improvements to several modules, check them out to see what has changed.

**New Todo Display**
The Todo Window has been re-implemented as a native UI element, this displays on the same UI layer as nameplates, meaning the todo list will not draw on top of your other windows.
Some features have been removed. Some new features have been added. Enjoy!

**Removed Features**
Wondrous Tails Duty Finder Overlay
Duty Roulette Duty Finder Overlay
Timers Window

These features have been intentionally removed from DailyDuty.
You can find the Duty Roulette Duty Finder Overlay in SimpleTweaks now as 'Color Duty Roulette Names'

### CODE REVIEW

**Comment by lmcintyre** [comment]
bleatbot, rebuild

**Comment by MidoriKami** [comment]
Actual diff from testing release:
https://github.com/MidoriKami/DailyDuty/compare/62162d4baf320c62af3daed853210cfe00a8ceb5..0dfb054cfaf0d016100b0af94c2ff043534ff6c4

**Comment by MidoriKami** [comment]
https://github.com/MidoriKami/DailyDuty/compare/62162d4baf320c62af3daed853210cfe00a8ceb5..0dfb054cfaf0d016100b0af94c2ff043534ff6c4
Updated Diff

**Comment by MidoriKami** [comment]
https://github.com/MidoriKami/DailyDuty/compare/62162d4baf320c62af3daed853210cfe00a8ceb5..cd31d4a8312207c485df428d26fbd42653ade53d

Added a couple more small changes.

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
