### PR TITLE
[Testing] ChatEmoteColor

### PR DESCRIPTION
**Pull request by 53m1k0l0n**
Update to NET 7.0 and API 8

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by 53m1k0l0n** [comment]
TBH i don't get it, yeah i'm not the owner of the plugin, i'm a Collaborator of that repo.

**Comment by NotNite** [comment]
The `owners` field needs to match the GitHub username(s) of who owns the project. You should make sure to get approval from the repo owner if you haven't, also.

**Comment by 53m1k0l0n** [comment]
Ah now I have it, I'll fix this after sleep.
Well I asked him if he maintains it and he said:

" i'm currently not maintaining this plugin
anymore, but might come back to it in the future. I sent you an invitation to
collaborate on this repo. "

**Comment by 53m1k0l0n** [comment]
repository = "https://github.com/chrisk699/ffxiv-chatemotecolor-plugin.git"
owners = ["chrisk699"]

i put the username of t owner in the owners field

**Comment by MidoriKami** [comment]
> repository = "https://github.com/chrisk699/ffxiv-chatemotecolor-plugin.git" owners = ["chrisk699"]
> 
> i put the username of t owner in the owners field

You put your github username in this field "53m1k0l0n"

**Comment by 53m1k0l0n** [comment]
Thank for all the help.

**Pull request merged**
