### PR TITLE
[WIP] Update FauxHollowsSolver (stable)

### PR DESCRIPTION
**Pull request by daemitus**

### CODE REVIEW

**Comment by daemitus** [comment]
Generated by https://github.com/daemitus/DalamudPluginPR2

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
oh

**Comment by philpax** [comment]
gotta fix that double https:// @daemitus

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
