### PR TITLE
[Testing] Chatter

### PR DESCRIPTION
**Pull request by jlkeesey**
Attempt #2. Hopefully the naming is correct this time.

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
Hello! I'm part of the plugin review team and was testing this for initial review purposes. Plugin functionality appears to be mostly in place, but I did notice it did not create the log folder name (or show an error that it couldn't). 

The autofilled entry looked fine as properly detected my documents folder location, but sample messages did not log. After I created the folder, it logged as expected.

To note, my Documents folder is on D:\, as I do library folder moves. The plugin config figured this out fine, but perhaps folder creation did not accommodate this?

**Comment by jlkeesey** [comment]
Firstly, it is not supposed to create the folder until the first log file is created, and the first log file is not created until the first message is written out. However, it is supposed to create the directory at that point. It did at the beginning because I tested it but obviously something changed. I will look into it.

**Review by karashiiro — APPROVED** [review]

**Comment by karashiiro** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
