### PR TITLE
[Testing] QuestTracker v1.0.0.0 

### PR DESCRIPTION
**Pull request by isaiahcat**

### CODE REVIEW

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Test Results:
Plugin does finish loading however I get an error 
`Error loading QuestData from data.jason`
`Could not find file 'Z:\home\myname\.xlcore\data.json`

When I try to open either of the windows I get
```
18:37:19.115 | ERR | Exception during raise of "Void DrawUI()"
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at QuestTracker.QuestDataManager.UpdateQuestData(QuestData questData) in /work/repo/QuestTracker/QuestDataManager.cs:line 97
	   at QuestTracker.MainWindow.Draw() in /work/repo/QuestTracker/MainWindow.cs:line 52
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
18:37:20.121 | INF | [LOCALPLUGIN] Finished unloading "QuestTracker"
```

I'm running XIV on linux, this shouldn't generally make a difference but if you are loading a file of some description, you'll need to make sure your paths are cross platform compatible. If you need help just tag me.

**Comment by wolfcomp** [comment]
To what Critical posted, I have located the issue and also submitted a PR for fixing it as grabbing files from where the DLL is located is prone to issues PR in question: https://github.com/isaiahcat/QuestTracker/pull/1

**Comment by philpax** [comment]
Hi @isaiahcat, please merge the above PR, or a similar fix, at your convenience - that's the only thing blocking the merge right now :slightly_smiling_face:

**Comment by isaiahcat** [comment]
Merged and updated the manifest.toml to point to the latest commit. Thanks for the help, everyone!

**Comment by Haselnussbomber** [comment]
The assembly name was misspelled in the GetManifestResourceStream call:
https://github.com/isaiahcat/QuestTracker/commit/f7d56b71d781719c5e473862efb7da82b7fb44d1#diff-8d20cea1ac66c19c4da60f6a04446e7814520326864e634c85dc035299b1217cR33

**Comment by philpax** [comment]
Hi @isaiahcat, just checking in on this - it looks like you'll have to apply the fixes above and then you should hopefully be good to go :pray:

**Comment by isaiahcat** [comment]
All fixed :) Apologies, I didn't get notified about these comments for some reason

**Comment by wolfcomp** [comment]
@isaiahcat Forgot to do one thing during the pr, which was including `using System.Reflection;` which is currently causing the build to fail in `QuestDataManager.cs`

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by isaiahcat** [comment]
Thank you!

I'm already in the discord server with my nickname set to isaiahcat :) I already have the "dev channels" role, unless you're talking about something else.

**Pull request merged**
