### PR TITLE
[Testing] HuntHelper update

### PR DESCRIPTION
**Pull request by imaginary-png**
added teleport feature to hunt train

### CODE REVIEW

**Comment by goaaats** [comment]
You should add the same safety checks TeleporterPlugin has, or just use TeleporterPlugin IPC: https://github.com/pohky/TeleporterPlugin/blob/master/TeleporterPlugin/Managers/TeleportManager.cs#L8

**Comment by imaginary-png** [comment]
>use TeleporterPlugin IPC
Sorry, I'm not sure how to do that or what that exactly means. From what I've tested if there's no player nothing happens, and if not attuned or crafting or something it just seems to triggers an in-game error of "unable to teleport / execute command"

**Comment by philpax** [comment]
> > use TeleporterPlugin IPC
> 
> Sorry, I'm not sure how to do that or what that exactly means. From what I've tested if there's no player nothing happens, and if not attuned or crafting or something it just seems to triggers an in-game error of "unable to teleport / execute command"

Apologies - IPC is somewhat undocumented. Plugins have a way of communicating with each other (Inter-Plugin Communication), and the Teleporter plugin offers an API using this IPC mechanism that validates its inputs. This allows you to use it to do teleportation without having to worry about sending something invalid to the game. Here's an example from Wotsit:
https://github.com/goaaats/Dalamud.FindAnything/blob/196628cdd5a9d4feb51a282028891dd82079d444/Dalamud.FindAnything/FindAnythingPlugin.cs#L1205
https://github.com/goaaats/Dalamud.FindAnything/blob/196628cdd5a9d4feb51a282028891dd82079d444/Dalamud.FindAnything/FindAnythingPlugin.cs#L1235
https://github.com/goaaats/Dalamud.FindAnything/blob/196628cdd5a9d4feb51a282028891dd82079d444/Dalamud.FindAnything/FindAnythingPlugin.cs#L397

Let us know if you need any further information :)

**Comment by imaginary-png** [comment]
Thank you, that helpful. I just sorta copied the example you linked.

**Review by goaaats — APPROVED** [review]

**Pull request merged**
