### PR TITLE
SortaKinda v1.0.4.2

### PR DESCRIPTION
**Pull request by MidoriKami**
More system improvements.

Name filter will now indicate if the input string/regex is invalid.

### CODE REVIEW

**Comment by MidoriKami** [comment]
Right! Forgot this depends on `IGameInventory` and can't be merged until Dalamud is updated to stable.

**Review by reiichi001 — APPROVED** [review]

**Comment by MidoriKami** [comment]
Bleatbot, rebuild

**Comment by MidoriKami** [comment]
This plugin is no longer blocked, dalamud stable has been updated.

**Comment by MidoriKami** [comment]
bleatbot, rebuild

**Review by philpax — APPROVED** [review]

**Pull request merged**
