### PR TITLE
[Testing] ZDs 1.0.0.0

### PR DESCRIPTION
**Pull request by Zeffuro**
This plugin allows you to see abilities coming off cooldown in a timeline way, much like the WoW plugins of the past: Cooldown Timeline/CDTL2/CoolLine/SP Timers

This is only a new way to represent already existing/present information that can be seen on your bars or could be made to show with stuff like DelvCD.

This is my first D17 PR and first solo plugin so if there are any things I've missed or forgotten about let me know and I'll get on it right away.

mpvnet_2024-07-27_14-04-36

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Hello! These are some post code review notes I had while checking through the plugin code.

Is there a reason you're purposely making a `<pluginname>/Settings.json`  file with manual serialization/deserialization over using `IPluginConfiguration` for a Dalamud-managed `AssemblyName.json` file to hold your plugin config? Config directories are typically used for splitting up plugin config (ex: per-tweak config), profiles for per-character config, etc. This does not appear to be doing anything like that.

Dalamud also provides a utility to open links in a platform-friendly manner, `Dalamud.Utility.Util.OpenLink(string)` that you can use.

**Comment by Zeffuro** [comment]
A lot of this has to do with using ActionTimeline as a base (I have permission to use inspiration from it) and slowly adding things from projects and conventions I've been used to. 

I can try changing it to IPluginConfiguration but I've never worked with it in the projects that I've contributed to. Would it make or break my chances of getting into the main repo? I'm not sure how much refactoring would need to be done since a lot of the settings are being directly accessed/changed during runtime, please advise me on that.

I've switched to OpenLink

**Comment by reiichi001** [comment]
I personally wouldn't consider not using `IPluginConfiguration ` a blocker, but I'll need other PAC members to weigh in on this.

You should still be able to access your configuration object during runtime, make changes, etc if you do switch. It's more of a tradeoff between having Dalamud serialize/deserialize it for you (and any additional helper methods) and rolling that work yourself.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first solo plugin! I'd extend you the invite to the secret den, but I believe you already have it :saluting_face:

**Comment by Zeffuro** [comment]
Thank you so much! I'm so hyped :D

**Pull request merged**
