### PR TITLE
Add BigNaelQuotes to testing

### PR DESCRIPTION
**Pull request by hunter2actual**
LLZ1yN9
Accessibility thing - use the Dawntrail GimmickText to display Nael quotes so I don't have to read a small jittery speech bubble.

### CODE REVIEW

**Comment by reiichi001** [comment]
I've added this plugin to the review queue.

**Comment by hunter2actual** [comment]
Tested today in UCOB and it was working really nicely, I didn't have to squint to call the quotes for my static. I don't know if reviewers will consider this to be within guidelines for a combat plugin but I'd like to advocate for it as an accessibility/ui thing - it presents information in a different way that would otherwise be in the chatbox or above the boss' head, and it doesn't solve the quotes for you.

**Comment by Critical-Impact** [comment]
Test Results:

Plugin loads/unloads fine
Do not have access to said duty to test

**Comment by reiichi001** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
