### PR TITLE
PartyIcons 1.1.1.0

### PR DESCRIPTION
**Pull request by squidmade**
- Update for 6.3, API 8, and .NET 7
- Thanks PhaineOfCatz for the new PartyIcons plugin icon
- Thanks Nicolette Phoenix for providing development support

### CODE REVIEW

**Comment by squidmade** [comment]
I'm a dummy

**Comment by squidmade** [comment]
bleatbot rebuild

**Comment by squidmade** [comment]
bleatbot, rebuild

**Comment by squidmade** [comment]
the galaxy is at peace

**Review by ackwell — APPROVED** [review]
changes look sane, but would be good to get a second pair of eyes on the dependency changes 'cus i'm not the most familiar

**Comment by reiichi001** [comment]
Should be good. A few plugins are using ContextMenu and others are using XivCommon.

**Pull request merged**
