### PR TITLE
PartyIcons 1.0.8

### PR DESCRIPTION
**Pull request by squidmade**

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Manual diff: https://github.com/shdwp/xivPartyIcons/compare/cd6e660c6380470c67d9dc2b1e3cd61714146a29..cd6e660c6380470c67d9dc2b1e3cd61714146a29

**Review by philpax — DISMISSED** [review]

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on submitting your first PR, and thank you for taking over from shdwp! Please let me know your Discord username and we'll add you to the dev-only channels.

**Comment by squidmade** [comment]
Thank you, I'm glad to help out! I'm May#4321 on Discord.

**Pull request merged**
