### PR TITLE
[Testing] PositionalGuide

### PR DESCRIPTION
**Pull request by PrincessRTFM**
I've finally figured out the automatic PR workflow. There's a handful of "not your plugin" errors from when I was trying to work that out, sorry about that.

### CODE REVIEW

**Comment by PrincessRTFM** [comment]
Sorry, trying to get [dae's auto-PR action](https://github.com/daemitus/DalamudPluginPR2) working, don't know why it left out my name in the owner field

**Comment by philpax** [comment]
This appears to be a new plugin - can you move it to testing?

**Comment by PrincessRTFM** [comment]
It's been released on an external repo for a few months with multiple users, not to mention my own machine, without any problems. I just forgot to submit to official testing when I had it finished. I can still move it if you feel it's necessary, but it's been in unofficial testing for a while now.

**Comment by philpax** [comment]
Yeah, it's more so that we can test it

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by philpax** [comment]
Sorry about the delay on this one, we've been quite busy. We're happy to merge this, but can you sure the tethers don't work in PvP?

**Comment by PrincessRTFM** [comment]
[They don't](https://github.com/PrincessRTFM/PositionalAssistant/blob/master/PositionalGuide/Plugin.cs#L59-L61), because I thought of that from the start. As long as Dalamud's `ClientState.IsPvP` is functioning properly, the plugin refuses to draw any of the guides in a PvP environment.

**Comment by philpax** [comment]
Excellent, thanks!

**Review by philpax — APPROVED** [review]

**Pull request merged**
