### PR TITLE
Update NotificationMaster and Mini

### PR DESCRIPTION
**Pull request by Limiana**
Previous PR got removed because I renamed branch

### CODE REVIEW

**Comment by Aireil** [comment]
bleatbot, rebuild

**Comment by Limiana** [comment]
Needs either windows desktop packages to be updated in plogon or primary .net package to be pinned to the version Dalamud ships with it (later is better approach I think since you'd be building plugins against version that is actually in use), right now bot uses latest minor version of .Net
https://github.com/goatcorp/DalamudPluginsD17/pull/3643#issuecomment-2197567295

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by Limiana** [comment]
bleatbot, rebuild

**Comment by Limiana** [comment]
I'll come back to this later, I have some methods to bypass winforms dependency

**Pull request closed without merging**
