### PR TITLE
SAMMI Webhook Plugin v1.0.0.0

### PR DESCRIPTION
**Pull request by HatTheTurtle**
Plugin to send game information to the stream automation program SAMMI, allowing users to automate stream effects based on in-game events (e.g., apply an effect to their webcam on gaining a vuln stack, playing a sound byte/animation when they crit in buffs, etc.)

Feedback appreciated!

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by NotNite** [comment]
The folder name (SAMMIWebhookPlugin) must match the plugin internal name (SammiPlugin).

**Comment by reiichi001** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by reiichi001 — APPROVED** [review]

**Comment by HatTheTurtle** [comment]
That would be great, my discord handle is hattu

**Pull request merged**
