### PR TITLE
[Testing] TwitchXIV v1.0.0.0

### PR DESCRIPTION
**Pull request by Aida-Enna**
Allows you to join a Twitch chat and send messages and (optionally) have the twitch chat come through your chatbox. Useful for playing XIV while watching a stream and still being able to interact without having to alt tab over to the steam to chat.

https://user-images.githubusercontent.com/5483362/227134415-9051133a-92c5-4c7f-b7fa-0eb3c46c9cd3.mp4

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by lmcintyre** [comment]
I would ask you to refactor the plugin such that a re-enable of the plugin is not required for initial setup. This is not a flow that we'd want to encourage users to do.

**Comment by Aida-Enna** [comment]
> I would ask you to refactor the plugin such that a re-enable of the plugin is not required for initial setup. This is not a flow that we'd want to encourage users to do.

Good call, leveled up my C# skills and made it work. :+1:

**Comment by lmcintyre** [comment]
> > I would ask you to refactor the plugin such that a re-enable of the plugin is not required for initial setup. This is not a flow that we'd want to encourage users to do.
> 
> Good call, leveled up my C# skills and made it work. 👍

```cs
16:49:25.416 | ERR Exception during raise of "Void Draw()"
System.NullReferenceException: Object reference not set to an instance of an object.
   at TwitchXIV.PluginUI.Draw() in TwitchXIV\PluginUI.cs:line 41
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
```

First-time saving no longer works. Looks like it tries to access the Client but that's null until you connect; but you can't connect because it can't save settings.

**Comment by Aida-Enna** [comment]
Third time's the charm (hopefully)

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
