### PR TITLE
WinTitle adoption

### PR DESCRIPTION
**Pull request by herulume**
Adopting WinTitle per:

1. https://discord.com/channels/581875019861328007/653504487352303619/1271230474462957588
2. https://discord.com/channels/581875019861328007/653504487352303619/1271238055646335097
3. https://discord.com/channels/581875019861328007/653504487352303619/1271239124690669620

I was given repo access so no need to fork it and update that.

### CODE REVIEW

**Comment by rreminy** [comment]
Confirming I approved the adoption

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by rreminy** [comment]
Is everything okay here? should I make a PR instead adding herulume as author and see how it goes?

**Comment by reiichi001** [comment]
This could potentially be a bug in how ownership is checked. I'd probably keep both of you listed as owner or set the repo URL to @herulume's fork instead.

**Comment by herulume** [comment]
I've tried keeping us both as authors on the first commit and bleatbot also died. Hence my attempt to remove @rreminy to see if that would make it pass.

I will add them again then.

**Comment by rreminy** [comment]
Seems like making a dummy commit worked at https://github.com/goatcorp/DalamudPluginsD17/pull/4344

**Comment by herulume** [comment]
Quirks of the process I guess.
I will close this PR then.

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
