### PR TITLE
[Testing] InfiniteRoleplay

### PR DESCRIPTION
**Pull request by serifas**
Hey, I am finally submitting my plugin again to be approved.
Sorry about before, it had a lot of issues which took me a while to fix.

### CODE REVIEW

**Comment by philpax** [comment]
Hi! Can you provide a brief description of what the plugin does?

**Comment by serifas** [comment]
Quick question. Can a secret be used to check whether a user has the correct client to connect to my server.
Such as a way to verify that they have the right build?

**Comment by serifas** [comment]
One moment I am just doing one last fix then I will post the update

**Comment by serifas** [comment]
I was informed that I forgot to dispose some images so I am doing that now and I will push when done

**Comment by serifas** [comment]
Please wait up for a moment. I just realized I am getting task exceptions in the dalamud log from my plugin. please give me a little bit to fix it

**Comment by serifas** [comment]
The issues should be fixed, but if there are any errors please inform me and let me know if you have any ideas on how to fix them.

**Comment by serifas** [comment]
I just pushed the wrong source one moment

**Comment by philpax** [comment]
Is this plugin ready for testing now? Any further changes will invalidate testing results, unless they're trivial, so we want to make sure that you're ready.

**Comment by serifas** [comment]
yes it is ready now. I finished, I will not commit any more changes.

**Comment by serifas** [comment]
Also please let me know before fully publishing the plugin, I have a question about secret keys and how to ensure people on the wrong client version can't connect to my server.

**Comment by serifas** [comment]
I keep getting an error that this can't find a .git file and I don't know why. Everything works on my end when I pull from the repo and build. Everything is on net8

**Comment by serifas** [comment]
I am noticing my plugin is causing an issue where it is randomly closing the game and I don't know why yet. I am going to close the pull request until I fix it. I will re open when I have it solved.

**Pull request closed without merging**
