### PR TITLE
[Testing] Infinite Roleplay

### PR DESCRIPTION
**Pull request by serifas**
My plugin is currently very sloppily coded and seldom commented but it works properly from what I have tested.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by serifas** [comment]
I realized there is a current issue with my plugin. It is causing the game to shut down. I will need to figure this out

**Comment by reiichi001** [comment]
It appears that the source code to this plugin has been hidden or removed. The plugin will not be able to be built, reviewed, or merged until that is resolved. 

If you've taken it down to work on it, that's fine, but then I would recommend closing this PR and opening a new one once it's ready for review again.

**Comment by philpax** [comment]
Hi there, I'm closing this for now. Feel free to resubmit when you'd like to present it for review once more!

**Comment by serifas** [comment]
Heya I updated this plugin. Everything should be workingnow. How do I re submit?

**Comment by philpax** [comment]
Hi, just open a new PR, same as before 🙂

**Pull request closed without merging**
