### PR TITLE
[Testing] LogogramHelper 0.0.1.7

### PR DESCRIPTION
**Pull request by apetih**
Submits plugin for review and testing.

Logogram Helper implements some Eureka QoL features related to Logos Actions.
It adds a menu for displaying all available Logos Actions upon entering the Logos Manipulator, and displays the possible Logogram combinations to create said actions, alongside the amount capable of creating with your current stock of logograms.
Additionally displays the contents of Logogram items on their item details, similar to Bozjan fragments.

### CODE REVIEW

**Comment by NotNite** [comment]
(by the way, your icon is invalid)

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by reiichi001** [comment]
Hello! We're still working on reviewing this plugin, but since it's crossed over into an API update, please update the project's runtime to net7 and update the DalamudPackager NuGet package to 2.1.10 (or later). 

For any other migration to NET7 docs, please see <https://github.com/goatcorp/Dalamud/discussions/1042>

**Comment by apetih** [comment]
There it is! I hope I did it all correctly, and hopefully it also fixes the issue with the icon image.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your plugin submission, and sorry about the wait!

As a first-time contributor, if you're in the ~~`goat place`~~ `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by apetih** [comment]
I am indeed in the ~~`goat place`~~ `XIVLauncher & Dalamud` Discord server! My handle is Alysse#6247

**Pull request merged**
