### PR TITLE
[Testing] DaCoblyn 1.0.0.0

### PR DESCRIPTION
**Pull request by thatismunn**
- Add feature that can handle realtime translate from chat.
- Add `/tl` command to translate some word to a target language. Supported language can be see in [here](https://translate.argosopentech.com/languages).

### CODE REVIEW

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

I've adjusted the PR title to include `[Testing]` so it will go to the correct announcement channel.

Please make sure to add a description to the first PR message.

Please update the PR with a corrected manifest.toml file. The "owners" section must match your github username.

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by goaaats** [comment]
bleatbot, rebuild

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Apologies for the delay, and congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
