### PR TITLE
WaymarkPresetPlugin v1.4.6.0

### PR DESCRIPTION
**Pull request by abashby**
- Update for 6.4

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by MidoriKami** [comment]
It's still pointed at mei's repo `"https://github.com/squidmade/WaymarkPresetPlugin.git"`

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by MidoriKami** [comment]
Some notes with the WaymarkPresetPlugin.json,
I believe IconUrl and ImageUrls are now unused, they use the images folder in this repository instead.
Additionally `DalamudApiLevel` should be removed from the json, as DalamudPackager automatically outputs the correct api version for the used DalamudPackager version.

**Comment by reiichi001** [comment]
Image and Icon URLS only apply to custom repositories. PluginMaster generation will take care of them otherwise. They don't hurt though.

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
