### PR TITLE
HotbarBackup v1.0.0

### PR DESCRIPTION
**Pull request by MistralsA**
Hotbar Backup v1.0.0

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Based on the setup of your source code, I think you'll need to add this to your manifest.toml.
```
project_path = "HotbarBackup"
```

That should get it building. (Or further along)

**Comment by MistralsA** [comment]
Would greatly appreciate an explanation on what happened here   m(_ _)m
https://github.com/goatcorp/DalamudPluginsD17/actions/runs/11180921548/job/31083717402#step:13:54

**Comment by philpax** [comment]
@goaaats build broke: `System.MissingMethodException: Cannot dynamically create an instance of type 'Plogon.Repo.State+Channel+PluginState+PluginChangelog+UsedNeed'. Reason: No parameterless constructor defined.`

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
> Is that failure an issue on our end, @goaaats ?

No, looks like an issue with the plugin

**Review by reiichi001 — APPROVED** [review]

**Comment by reiichi001** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by MistralsA** [comment]
I would like to get feedback for my plugin! My Discord handle is `mistralsa`

**Pull request merged**
