### PR TITLE
VenueManager v2.2.0

### PR DESCRIPTION
**Pull request by Jrogo7**

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by reiichi001 — APPROVED** [review]

**Comment by Jrogo7** [comment]
Hey! Thanks for the update. I think I'm in the right channels, but just incase my handle is `jrogo`.

**Comment by Jrogo7** [comment]
As a quick question if its ok to ask here. Is there a specific process from moving from the testing state to non testing?

**Comment by reiichi001** [comment]
For the most part, there is no formal "when should you promote from testing" guidelines. 

We have officially merged in some updated networking guidelines for plugins, but I haven't seen it get regenerated for the official dalamud.dev site just yet. You can find the pertinent bits here: <https://github.com/goatcorp/dalamud-docs/pull/27/files>.

**Comment by Jrogo7** [comment]
Sounds good. Thanks for the heads up :)

**Pull request merged**
