### PR TITLE
[Testing] TiltedPlugin v3.4.1.2

### PR DESCRIPTION
**Pull request by meoiswa**
- Added Is Flying Trigger

### CODE REVIEW

**Comment by reiichi001** [comment]
Code looks fine. Please make sure to increase the version number. Then we can merge this in.

**Comment by meoiswa** [comment]
Updating to 3.4.1.1 with a small fix to a typo in a math operation

**Review by meoiswa — COMMENTED** [review]
Update to 3.4.1.1 to fix minor typo in math expression

**Comment by meoiswa** [comment]
Fixed a couple more minor math errors

**Pull request closed without merging**
