### PR TITLE
[Testing] XIVUncombo 1.0.0.0

### PR DESCRIPTION
**Pull request by MKhayle**
### More button bloating! Add new actions and un-combo your combos!
Wanna hurt your hand as much as mine does? I really need to stop playing MCH.
### Uncombo your favorite job (which is Pictomancer) to spice things up!
Bored of the same 1-1-1, 2-2-2 rotation? Feeling nostalgic of the GNB era when you had to press tons of buttons? 
### You **need** to unlock BLU Spells to make use of this plugin.
This plugin uses BLU spells as placeholders to replace them with the original actions. They're easy to obtain, so try BLU out! The replacement also only applies to the job you checked Uncombos for.

### CODE REVIEW

**Comment by MKhayle** [comment]
Small note for PAC: this is a fork of a fork of XIVCombo. 
It's also doing things you may be wary of (action & icon replacement); feel free to tell me if something shouldn't be there, or if the concept itself feels like it doesn't belong to the main repo.

**Comment by MKhayle** [comment]
oh god I'm dumb

**Comment by philpax** [comment]
Should we close this for now?

**Comment by MKhayle** [comment]
I'm 70% done on the rework of this (and going to swap to ImRaii wherever it's possible now), so expect an update within next week

**Comment by MKhayle** [comment]
Small notes : 
- This has been extensively tested but the sheer number of combinations makes it harder to test everything (and I don't have all jobs 100 yet...)
- I stripped away almost all of the xivcombo code, keeping only the required logic
- I totally changed the UI to make it distinct from XIVCombo's UI
- There is a known bug where the window just breaks if you drag it on the left, effectively hiding the job list, probably a child getting culled or something. I'll get back to it when I'll have help, probably as it doesn't effectively leak (thanks ImRaii) or crash the game.

image

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Test Results:
Loads with no issues
No tags in manifest
Plugin seems to function as expected

**Review by philpax — APPROVED** [review]

**Pull request merged**
