### PR TITLE
[Testing] DailyDuty v4.0.2.0

### PR DESCRIPTION
**Pull request by MidoriKami**
Improved UI Rendering System, significantly increases performance.
New Command System, significant improves coolness of using `/dailyduty help`

Improved file saving/loading, prevents `0` folder from being made.

Improved performance (thanks nebel)

**Todo Display: Removed Mouseover Tooltips**, this feature was causing too many crashes, and has been removed.

There are a couple new strings that need translating, if you are willing to help it would be greatly appreciated
<https://crowdin.com/project/dailyduty>

### CODE REVIEW

**Comment by MidoriKami** [comment]
HA, the bot lies.
This is `size-large`, it's not including the KamiLib diff.

**Comment by MidoriKami** [comment]
Diff from Stable (v4.0.1.6) -> This Version (v4.0.2.0)
https://github.com/MidoriKami/DailyDuty/compare/dd9a8d45272b43de7baec2306cecb10b13cae9b3..ff7a113b5299cca5db3ddc36d68438b30cc760bc

**Comment by MidoriKami** [comment]
(Removed a file that was completed commented out)

Diff from Stable (v4.0.1.6) -> This Version (v4.0.2.0)
https://github.com/MidoriKami/DailyDuty/compare/dd9a8d45272b43de7baec2306cecb10b13cae9b3..10c3941b40633c66878e074ffeff926ba6cc30a9

**Comment by MidoriKami** [comment]
Diff from Stable (v4.0.1.6) -> This Version (v4.0.2.0)
https://github.com/MidoriKami/DailyDuty/compare/dd9a8d45272b43de7baec2306cecb10b13cae9b3..bae1d9f157d9b8c8b4b6d66b4af008228bf4d6ec

**Comment by MidoriKami** [comment]
Diff from Stable (v4.0.1.6) -> This Version (v4.0.2.0)
https://github.com/MidoriKami/DailyDuty/compare/dd9a8d45272b43de7baec2306cecb10b13cae9b3..402c8f69fd2c2e28970e338423e114016aed4d7e

**Comment by MidoriKami** [comment]
Diff from Stable (v4.0.1.6) -> This Version (v4.0.2.0)
https://github.com/MidoriKami/DailyDuty/compare/dd9a8d45272b43de7baec2306cecb10b13cae9b3..ad70ba7aefc0d6db85fac2ab9c3fcab5d1a87db7

**Comment by MidoriKami** [comment]
Diff from Stable (v4.0.1.6) -> This Version (v4.0.2.0)
https://github.com/MidoriKami/DailyDuty/compare/dd9a8d45272b43de7baec2306cecb10b13cae9b3..fe218325eca4ea8653e0570dbff27fd0f21c07ab

**Comment by MidoriKami** [comment]
With my new imgui framework and caching of attribute lookups, imgui draw time is down from ~0.6000ms/frame to 0.3000ms/frame when the configuration window is open.

With nebel's contributions idle framework time has been reduced from ~0.1100ms/frame to ~0.0450ms/frame

**Review by karashiiro — APPROVED** [review]

**Pull request merged**
