### PR TITLE
[Testing] Add HuntHelper

### PR DESCRIPTION
**Pull request by imaginary-png**
A plugin for finding hunts, recording positions for trains, sending map links into chat, tts+ notifications.

example: 

https://user-images.githubusercontent.com/70348218/184215756-fd223aad-ec4d-44cc-a02b-8b4eda07425e.mov

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by imaginary-png** [comment]
oop

**Comment by NotNite** [comment]
You should move to `testing/live` now that net6 is stable.

**Comment by imaginary-png** [comment]
anything else I need to do / change? It's been tagged as code reviewed for a bit, no rush tho I'm just wondering.

**Comment by NotNite** [comment]
I'm not part of the plugin review team, so I can't tell you - but it's most likely just waiting on someone with free time to test and approve the plugin.

**Review by reiichi001 — APPROVED** [review]

**Comment by philpax** [comment]
Apologies for the delay there; there were technical issues on our end. Welcome to the Goatcorp Plugin Crew:tm:!

**Pull request merged**
