### PR TITLE
[Testing] HUDLayoutHelper v1.0.0

### PR DESCRIPTION
**Pull request by Mary-Usagi**
My first plugin, so I'm probably doing some inefficient stuff in there. >.< 

The plugin adds some QoL features to the native HUD Layout editor:  
- ctrl+z/ctrl+y for undoing/redoing the movement of hud elements  
- ctrl+c/ctrl+v for copying and pasting the position of elements  
- ctrl+r to show lines that help with alignment of hud elements 

:)

<details>
  <summary>Screenshot</summary>

  alignment_lines

</details>

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by Mary-Usagi** [comment]
Would it be okay if I update the main branch with a more organized project structure (and also update the commit hash here)? Or would that interfere with any reviews that are already being done? :D I've only moved files around, so no changes to any logic

**Comment by reiichi001** [comment]
That will reset the code review, but I don't think anyone's gotten to that for this one, so it should be fine

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Hud Layout Helper
 - Plugin loads/unloads correctly
 - Most functionality works, clicking Ctrl + R blacks out my screen, not sure if this is linux specific but I can post a screenshot if required

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
