### PR TITLE
[Testing] added GlamourWishlist

### PR DESCRIPTION
**Pull request by Imaginary-Narwhal**

### CODE REVIEW

**Comment by Imaginary-Narwhal** [comment]
Discord Name is dragonflyy

**Comment by lmcintyre** [comment]
@Imaginary-Narwhal Hi! Apologies for the delay in approval here.

Your plugin has been reviewed in its entirety including code review and testing. However, one aspect should be improved before approval. When creating a glamour wishlist, all possible items are listed in the right pane. This drops game framerate down to 30fps. I would recommend using an ImGui ListClipper to draw your item lists - this is an effective solution as each of your list items are the same size and you do not need to draw them all at once.

Please let us know when you have resolved this so we can proceed with approval. Thank you for your submission and for your patience.

**Comment by Imaginary-Narwhal** [comment]
> 

I have updated the code and pushed it to my github, do I need to do another PR for here, or is there a different process for updating?

**Comment by tommadness** [comment]
> > 
> 
> I have updated the code and pushed it to my github, do I need to do another PR for here, or is there a different process for updating?

You need to update the commit hash in `manifest.toml` on this PR to the commit hash of your latest update.

**Comment by lmcintyre** [comment]
Thank you for the fix! Performance is great now.

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
