### PR TITLE
[Testing] PlayerTrack v3.4.10

### PR DESCRIPTION
**Pull request by kalilistic**
_Minor bug fixes including avoiding adding players during replays._
### Changed
- Update chinese/spanish localization.
- Migrate to the dalamud nameplate service.
### Fixed
- Don't process player data during replays.
- Hide serilog version warnings.
- Handle error when with empty db on merge screen (thakyZ).
- Prevent database from being locked on crash (thakyZ).
- Fix compiler warning for player retrieval function (thakyZ).

### CODE REVIEW

**Comment by kalilistic** [comment]
### Notes for PAC
- None

**Comment by kalilistic** [comment]
bleatbot, rebuild

**Comment by kalilistic** [comment]
bleatbot, rebuild

**Comment by kalilistic** [comment]
I think some of these diffs are from an old test version rather than latest stable.

**Review by philpax — APPROVED** [review]

**Pull request merged**
