### PR TITLE
[Testing] HotbarUnlimited v1.0.0.0

### PR DESCRIPTION
**Pull request by MidoriKami**
Adds new plugin for placing hotbar slots however and wherever you want.

Note: This plugin does not disable in PvP

### CODE REVIEW

**Comment by MidoriKami** [comment]
bleatbot, rebuild

**Comment by lmcintyre** [comment]
@MidoriKami The plugin seems to mangle my default hotbar positions when enabled.

Plugin disabled:
 ffxiv_dx11_QuK6iBZkp9

Plugin enabled:
 ffxiv_dx11_vec1Qw9Vai

**Comment by MidoriKami** [comment]
Seems I forgot to account for scaling thanks for the heads up

**Comment by MidoriKami** [comment]
That should do the trick, thanks again

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
