### PR TITLE
[Testing] XIVDupeFinder Initial Release 1.0.0.0

### PR DESCRIPTION
**Pull request by CallumCarmicheal**
A simple plugin utilising the Inventory logic from [InventorySearchBar byTischel](https://github.com/Tischel/InventorySearchBar).
This plugin will filter any stackable items that are not stacked (duplicates) then highlight them in a random pastel colour or one set by the user.

Credit is given inside the Configuration UI.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

To fix the build, please update your manifest toml to match your github username. Our build system uses this to confirm that the person (or people) submitting a plugin are authorized to do so.

**Comment by lmcintyre** [comment]
bleatbot, rebuild

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by CallumCarmicheal** [comment]
Hello @philpax,

My discord handle is callumcarmicheal.

**Pull request merged**
