### PR TITLE
[Testing] Craftimizer 1.2.0.0

### PR DESCRIPTION
**Pull request by WorkingRobot**
New plogon :)
Lots of improvements and optimizations could be made, but I just wanted to get it done and released for testing.
(icon and name is temporary)

Let me know if anything needs to be changed/updated.
Discord username is `camora.`

<details>
<summary>Example screenshots</summary>

### Crafting Log Helper
image

### Simulator Window
image
</details>
<details>
<summary>Example screenshots (Added in v1.2)</summary>

### Synthesis Helper
image

### Settings Window
image
</details>

### CODE REVIEW

**Comment by reiichi001** [comment]
Bleatbot, approve

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by MidoriKami** [comment]
Owners needs to be your gitbhub account name "WorkingRobot"

**Comment by reiichi001** [comment]
> ah is the owners property in the toml file supposed to be my github username?

yes

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

Just as a note, you can keep your plugin source on your gittea instance if you want. The only bit that needs to be github is your clone of DalamudPluginsD17 hosting your manifest file. Keeping the source on github is also fine!

**Comment by lmcintyre** [comment]
@WorkingRobot Deepest apologies for the delay in approval here.

Your plugin has been reviewed in its entirety, but your internal name in your plugin json must match exactly the folder that you place the manifest in in this repository, case sensitive. Please fix that so we can proceed with approval. Thank you!

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
