### PR TITLE
[Testing] BetterMountRoulette

### PR DESCRIPTION
**Pull request by CMDRNuffin**
Allows selecting each mount to include in mount roulette individually (for when you have more than 30 mounts you like, but also some you hate).

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on submitting your first plugin! In future / when you go to stable, can you get a better quality icon? A HQ version of the source icon should be available somewhere; if not, try using https://replicate.com/nightmareai/real-esrgan.

**Comment by philpax** [comment]
If you're in the Goat Place Discord, let me know what your Discord username is and I'll have you added to the dev channels.

**Comment by CMDRNuffin** [comment]
> If you're in the Goat Place Discord, let me know what your Discord username is and I'll have you added to the dev channels.

Nuffin#8273

**Pull request merged**
