### PR TITLE
[Testing] TargetLines plugin

### PR DESCRIPTION
**Pull request by Drahsid**
A plugin that I threw together in a couple hours which visualizes target lines in ImGui. I added a bunch of customization options. It is kinda like peeping tom, but for all players, and enemies. Probably doesn't provide any advantage for actual gameplay.

### CODE REVIEW

**Comment by Drahsid** [comment]
Some worries were brought in in the Discord over the possibility that this could show target lines from Objects that are not visible and not tangible, thus providing an advantage in comnat. I have updated the plugin to prevent that by doing the following:
- If the Object is not targetable, it will not draw target lines from it
- If the Object is a BattleChara, and not a PC, and it is occluded from the camera, it will not draw target lines from it. I do this check with a raycast and by checked the the tangent between the camera's direction and the Object's position relative to the camera position (if it is behind the camera.)
- If the Object has a scale of 0

This seems to work in my quick tests. Let me know if there are any issues (worst case scenario I disable it entirely during combat.)

**Comment by Drahsid** [comment]
The versioning issue mentioned in Pull Request #1191 also existed here. I fixed it in this last update.

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by philpax** [comment]
Hi, sorry about the delay. We're happy to merge, but can you make sure it's disabled in PvP?

**Comment by Drahsid** [comment]
Oh shoot, I didn't even test it in PvP. I'll update it shortly and let you know when that happens.

**Comment by Drahsid** [comment]
I just pushed the update. Let me know if there are any other issues.

**Review by philpax — APPROVED** [review]

**Pull request merged**
