### PR TITLE
[Testing] CleanHuntChat 1.0

### PR DESCRIPTION
**Pull request by Guerzoniansus**
Submitting CleanHuntChat for approval

CleanHuntChat is plugin that provides a clean chat experience during hunt trains.

Usage:

/cleanhunt - Enables the plugin for a configurable amount of time (default is 1 hour)

/cleanhunt off - Manually disables the plugin before the time is over.

When the plugin is enabled via /cleanhunt, every Shout and Yell message that doesn't contain a coordinate flag, or the word "instance", gets hidden.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Hi, can you add a description of what the plugin does?

**Comment by Guerzoniansus** [comment]
Yeah sorry I forgot to update my repo's Readme with a description. It's there now (but not in the commit hash I originally submitted) https://github.com/Guerzoniansus/CleanHuntChat/

**Comment by Guerzoniansus** [comment]
I added the description here in the PR too now if that's what you meant

**Comment by philpax** [comment]
Much appreciated! Sorry, we have a backlog of plugins to review - we'll get through them when we can 🙂

**Comment by philpax** [comment]
bleatbot, rebuild

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
@herulume tested this and will leave their feedback shortly. Apart from that, it's all good to go!

---
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by herulume** [comment]
I played with the plugin for a bit.

It would be nice not to be able to set 0 or negative numbers in the config UI. The plugin doesn't activate when you do so, so no harm is done. 

Small note: It took a while to load, but I haven't tested further to confirm if it was a one-time deal or not.

**Pull request merged**
