### PR TITLE
[Testing] HUDManager v2.5.7-b1

### PR DESCRIPTION
**Pull request by zacharied**
Move plugin to new build system.

### CODE REVIEW

**Comment by reiichi001** [comment]
Bleatbot, approve

**Comment by philpax** [comment]
bleatbot, approve

**Comment by MidoriKami** [comment]
owners = ["Necoji"] this needs to be your github username

**Comment by MidoriKami** [comment]
Also note that update post in the discord will be taken from the contents of your PR message

**Comment by MidoriKami** [comment]
Simply change `"https://github.com/zacharied/FFXIV-Plugin-HudManager"` to `"https://github.com/zacharied/FFXIV-Plugin-HudManager.git"

**Review by philpax — APPROVED** [review]

**Pull request merged**
