### PR TITLE
[Testing] CatScan 0.8.1.0

### PR DESCRIPTION
**Pull request by syldrathecat**
Hi this is a new plugin. Its rather similar in feature-set to HuntHelper since I didn't know about it before starting.

## Here's a list of features:

* The top of the plugin window displays the name of the current zone. For instanced zones, the instance number is also displayed.

* "Scan Results" tab will record a list of any S-rank, A-rank, B-rank hunt monster visible to the client. A-rank monsters are also recorded in the "Train Log" tab.

image image

* The list of recorded, not-killed mobs on the Train Log can be copied and pasted to share with others. The following text should be importable:

```
Yilan Thavnair ( 18.3  , 11.8 ) i1
Sugriva Thavnair ( 20.4  , 30.8 ) i1
```

* "Epic FATEs", e.g., Odin, Coeurlregina, Ixion, Formidible, Chi appear as a purple bar at the top of the Scan Results window:

image

* Regular FATEs are listed in the "Fates" tab with their distance and time remaining. For FATEs in the Preparation stage, the timer counts up and is colored grey.

image

* In **Southern Thanalan** only, a timer is displayed at the bottom of the FATE tab, indicating the amount of time since the last failed FATE.

image

* In zones with S-ranks which require kill counts, such as **The Rak'tika Greatwood**, the Kill Count tab will track the number of certain mobs killed:

image

* Scanned monsters and FATEs can be clicked to open their location on the map.
* Features as described in the configuration window:
  * Sound alerts -- adjusting the volume will cause a sound effect to play
  * Automatic map flagging, opening, and closing

### Eureka zone specific features:

* Entering a Eureka zone with the "Eureka tracker mode" config option enabled (on by default) presents this alternative UI listing all possible NM spawns:

image

* The KC field tracks the number of related enemies killed. Hovering over text in the KC column displays which enemy.
* The timer displays either the time remaining on the spawned NM, or the time remaining until it can be spawned again.
* If Eureka tracker mode is disabled, NM bosses are presented in the Scan Results tab, similar to S-ranks outside of Eureka; and the Kill Count tab is populated dynamically only for relevant monsters with a recorded kill count greater than 0.

### Bozja zone specific features:

* In Bozja or Zadnor, CEs are tracked in the Fates tab alongside skirmishes -- marked with an icon to differentiate them:

image

* Purple banners appear for CEs, and any Fate that is part of a CE chain. Notification sound is triggered only for the first event in any CE chain.
* Castrum and Dalriada large-scale battles are excluded from being being highlighted.
* "Star mobs" are recorded in the Scan results tab, similar to B-rank monsters.

## Possible integrity issues:

* S rank monsters (and A rank monsters engaged in combat), and epic FATEs which are hidden on the map, are able to be instantly located from anywhere in the zone, possibly through walls. Other plugins already have this functionality.
* Scanned enemies have their HP% displayed despite not being in the range normally required to see their HP bar. Other plugins already have this functionality.
* Some regular FATEs are displayed before they are visible on the map. This data can already be seen via `/xldata fate`.

### CODE REVIEW

**Comment by syldrathecat** [comment]
I'd also like to submit this description of the source files to assist with code review:

Generic/utility stuff:
* **Ui/*.cs** - Plugin window rendering code -- one file per tab (split in to MainWindow and ConfigWindow)
* **Configuration.cs** - Plugin configuration data class
* **GameFunctions.cs** - Functions that interact with the game -- just a wrapper for OpenMapWithMapLink
* **Plugin.cs** - Main plugin class that just initializes and glues stuff together
* **DalamudService.cs** - static Dalamud service interfaces
* **FFXIV/DynamicEvent.cs** - Game-struct stuff for reading DynamicEvent (e.g. Critical Engagement) data.
* **GameData.cs** - Provides data read from Lumina.

Real plugin logic stuff:
* **HuntData.cs** - Static data that describes hunt zones, interesting monsters and fate names, etc.
* **HuntModel.cs** - Dynamic data structure that stores the current state of the plugin's scanned monsters, visible fates, etc.
* **GameScanner.cs** - Accesses the game's Object, Fate and DynamicEvent tables each frame, and emits events that are picked up by **HuntScanner**.
* **HuntScanner.cs** - Picks up events from **GameScanner** and updates **HuntModel** appropriately. Also emits events that are picked up by **Notifications**.
* **Notifications.cs** - Plays sound effects and operates the plugin UI automatically in response to events.

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin will not be accepted due to extenuating circumstances.

**Comment by syldrathecat** [comment]
> This plugin will not be accepted due to extenuating circumstances.

Those circumstances being harassment from darkarchon I suppose

**Pull request closed without merging**
