### PR TITLE
PetNicknames

### PR DESCRIPTION
**Pull request by Glyceri**
[New Plugin: Pet Nicknames (0.2.0)]
[Testing] Pet Nicknames 0.2.0

Adds the ability to give nicknames to pets by using /petname
Ability to remove and disable the displaying of nicknames
Nicknames get saved based on pet

[Changelog 0.1.0 -> 0.2.0]
+ Complete plugin rewrite (now more stable)
+ Clear all pet names option
+ Disable the display of custom names option

### CODE REVIEW

**Comment by Glyceri** [comment]
bleatbot, rebuild

**Comment by Glyceri** [comment]
Ohhhhhhhhhhhh... I get it

**Comment by philpax** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Hello! Going through all plugins for review/testing.

I have a couple notes on this plugin that aren't blockers, but could be handy to address before release.

1. I would add a note that "pet" in this case means Minions, as FFXIV uses "Pet" to refer to things like Scholar/Summoner pets like Eos, Selene, Carbuncles, and Egis. The plugin doesn't allow renaming those.
2. I would include a note in the description and/or config box that the name change will take place on zone change or by re-summoning the pet. Or if you know how, it could help to redraw the pet on name change / add a button to unsummon/resummon it to apply.

**Comment by Glyceri** [comment]
I implemented the feedback as requested, would it be benefitial to push that for testing right now?
(You can also look away from a minion and look back and the name updates, weirdly enough any other interference like me moving the minion or forcing a respawn does not work, but when I have a sub again ill look into it).

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

---

I reviewed the code at the most recent GitHub commit - you'll probably want to push up a follow-up PR with the latest update! Promise it'll be faster this time :)

**Pull request merged**
