### PR TITLE
[Testing] SharlayanRadio v1.0.0.0

### PR DESCRIPTION
**Pull request by Ech-oes**
Sharlayan Radio is a plugin powered by public APIs such as Radio-Browser to retrieve public internet radio stations and play them over the internet during your gaming.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
The build issue is Microsoft's fault I think. We'll kick off a rebuild after confirming it's resolved.

**Comment by Ech-oes** [comment]
It seems like Docker could not find the SDK image. Do we know if anyone else is having this issue?

**Comment by wolfcomp** [comment]
It is because the Microsoft image hub just fails, or they're doing something with that causes it to fail.

**Comment by wolfcomp** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
bleatbot, rebuild

**Comment by Ech-oes** [comment]
Build is now OK. In short:

- NAudio dependency was calling upon WinForms to work, and for whatever reason, Microsoft likes to move stuff around and it could not find the required SDK/image to build.
- With some suggestions and help from other devs, the plugin now works off ManagedBass; a cross-platform library to play audio.

**Comment by Ech-oes** [comment]
Committing once more to provide required bass.dll (not included in ManagedBass) otherwise the plugin can not work.

**Comment by Ech-oes** [comment]
Build seems to have frozen on 'Cache docker image'. Attempting to rebuild.

bleatbot, rebuild

**Comment by MidoriKami** [comment]
bleatbot, rebuild

**Comment by lmcintyre** [comment]
Hi! Sorry to disappoint but we have not gotten to this plugin yet, and will likely not be able to review it until after Dalamud API 9 has been released. I would recommend taking the time and swapping to the API 9 branch of Dalamud by using /xlbranch in-game and swapping to v9 so you can test compatibility with your plugin. Once 6.5 releases, you can verify functionality once more and submit a new build.

Thank you and apologies for the delay.

**Comment by Ech-oes** [comment]
That's alright with me. I will be closing the PR for now then.

**Pull request closed without merging**
