### PR TITLE
[Testing] AutoMammet - Automatic Island Sanctuary Exporting System

### PR DESCRIPTION
**Pull request by Rietty**
This plugin was created to address the need for automated exporting (i.e. copying the data to the clipboard) from the Supply & Demand table in the Island Sanctuary. 

It also addresses the following issue/suggestion. https://github.com/goatcorp/suggestions/issues/963

The plugin itself simply allows for one to press a button to instantly copy the data from the game onto their clipboard, which can then be put into various programs or spreadsheets to help calculate workshop profits and goals.

A general simplified guide can be seen at the main repo: https://github.com/Rietty/AutoMammet

Thanks to Ottermandis for the code for getting the data from the game.

### CODE REVIEW

**Comment by NotNite** [comment]
Please prefix your PR title with `[Testing]` - our webhook bot isn't smart (yet).

**Comment by philpax** [comment]
buildbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

On a side note, you might want to consider separating it from your plugin repository... repository, just to make things cleaner (our diffs will diff the entire repository, not just the relevant folder).

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Sorry that we couldn't get this one in within the patch window - the approval team's been quite busy lately :( Will hopefully have an update for you soon!

**Comment by Rietty** [comment]
Thanks for getting back to me regardless. Hopefully it's soon but no rush.
:)

**Review by philpax — APPROVED** [review]

**Pull request merged**
