### PR TITLE
Wotsit 1.0.5.1

### PR DESCRIPTION
**Pull request by goaaats**
* 7.0!
* Add shortcut for "closest inn room"
* Fix some features being incorrectly disabled in "explorer mode" (by @nebel)
* Fix "collection" entries opening the wrong UI (by @nebel)

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
What's the go here?

**Comment by goaaats** [comment]
> What's the go here?

Good to go, I used this for plogon testing but now it should be ready

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
