### PR TITLE
Who Am I Again v1.0.0.4

### PR DESCRIPTION
**Pull request by MKhayle**
api11 update (can't believe I had to actually update it past the api version)

### CODE REVIEW

**Comment by MKhayle** [comment]
I guess plogon isn't ready yet?

**Comment by MidoriKami** [comment]
Try 11.0.1 for sdk

**Comment by MKhayle** [comment]
I was told plogon wasn't ready yet for api11 so that should be fine like this when it'll get rebuilt

**Comment by MidoriKami** [comment]
Someone said in the discord that sdk 11.0.0 was missing some dependencies and that 11.0.1 would be release, but you do you, not my problem.

**Comment by MKhayle** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Review by goaaats — APPROVED** [review]

**Pull request merged**
