### PR TITLE
[testing] ChatTranslated v1.0.0.0

### PR DESCRIPTION
**Pull request by kelvin124124**
Chat translator

### CODE REVIEW

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
Hi there, apologies for the delay. @lmcintyre is now responsible for the PR and will try to get it in ASAP.

In the meantime, is there any specific reason for creating a new plugin instead of contributing to one of the existing translation plugins? We don't mind plugins that share functionality with other plugins, but our preference is to consolidate plugins where possible to minimise user confusion. Thanks!

**Comment by kelvin124124** [comment]
@philpax can you provide a list of existing translation plugins? I'll consider the option.

**Comment by philpax** [comment]
> @philpax can you provide a list of existing translation plugins? I'll consider the option.

Hi, I just looked over the existing plugins with the [plugin browser](https://tommadness.github.io/Plugin-Browser/) - our apologies, we hadn't realised that the two plugins that primarily targeted translation (ChatTranslator and XivCoblyn) were no longer maintained. There's Echoglossian, but I'm not sure if it handles chat.

Given that, we withdraw that concern and are looking forward to getting this in soon 🙂

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
