### PR TITLE
[testing/live] Fast Job Switcher 1.0.0.3

### PR DESCRIPTION
**Pull request by meoiswa**
Enables the player to switch jobs using their three letter acronyms as commands.

### CODE REVIEW

**Comment by MidoriKami** [comment]
Seems this might be better suited as a tweak so you don't have to wait 1-2 months for merge

**Comment by meoiswa** [comment]
I also agree it would be better suited as a Tweak, however, it was rejected by its maintainer.

**Comment by MidoriKami** [comment]
Ahh I see now the note that was left on the proposed tweak.

An alternative approach then would be to expand the Command Alias tweak with the ability to import/export alias presets.
Might also be able to add presets that the user can enable by name.

For example, as seen in this **amazing** mockup
image

**Comment by reiichi001** [comment]
The code is short/simple enough that I can sign off on it. I'll add this to our review process.

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by philpax** [comment]
thx 4 new plugin

@reiichi001 on it

ok bye

**Review by philpax — APPROVED** [review]

**Pull request merged**
