### PR TITLE
[Testing] OofPlugin 1.0.4

### PR DESCRIPTION
**Pull request by codelastnight**
plays the roblox oof sound on fall damage and death.
I've also tested this with a couple of my friends, so it should be working pretty good

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by goaaats** [comment]
Owners needs to be the GitHub username you're submitting the PR with

**Comment by codelastnight** [comment]
oops, fixed now

**Comment by codelastnight** [comment]
🤡 im gonna cry

**Comment by Caraxi** [comment]
Its because you put the plugin here in `/Oof/` when it should be `/OofPlugin/`

**Comment by philpax** [comment]
Congrats on getting it sorted! We'll have to document/address some of the issues you encountered, a lot of those should really be more descriptive on our end.

We've added it to our approval backlog and should hopefully get it through soon :)

**Review by philpax — APPROVED** [review]
Sorry for the delay! You're all good to go now. Drop your Discord handle here and I'll have you added to the dev-private channels.

(Informal review committee note: consider adding a link to the hbomberguy video on the creation of the oof sound in the description)

**Comment by codelastnight** [comment]
I just finished the hbomberguy video LOL another 2hr banger 
my discord is `last night#8205`

**Pull request merged**
