### PR TITLE
CharacterPanelRefined 1.1.2.2

### PR DESCRIPTION
**Pull request by Kouzukii**
Fix an issue causing the wrong stat to be displayed

### CODE REVIEW

**Comment by philpax** [comment]
Looks like that's a version bump, is there meant to be a code change there?

**Comment by Kouzukii** [comment]
I didn't know if using the same version would recompile it, didn't change anything tho https://github.com/Kouzukii/ffxiv-characterstatus-refined/commit/11b91ea2ca3e0ad3541a74af6b52c90cafdadb17

**Comment by philpax** [comment]
I see. Well, I'll take your word for it that this is what you wanted to do

**Review by philpax — APPROVED** [review]

**Comment by Kouzukii** [comment]
Also i've already received bug reports, so people should get the fixed version with the bump

**Pull request merged**
