### PR TITLE
[Testing] AutoTimer v1.0.0.0

### PR DESCRIPTION
**Pull request by s5bug**
Adds a bar that does its best to time the progress to the next auto-attack. Includes backgrounds for Monk Riddle of Wind timing and Ninja Ten-Chi-Jin timing.

https://github.com/goatcorp/DalamudPluginsD17/assets/7751296/7f18bc87-86fc-43b7-8fee-f6fe39d895f5

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by reiichi001** [comment]
Test of AutoTimer-53dc51164b655d84321a11806d08ce4b3d00c18a completed.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by s5bug** [comment]
`@aly.fish`

**Pull request merged**
