### PR TITLE
NotificationMaster: 6.3 update

### PR DESCRIPTION
**Pull request by Limiana**

### CODE REVIEW

**Comment by Limiana** [comment]
grocery-store-misbehavior

**Comment by goaaats** [comment]
your library is still on net6

**Comment by Limiana** [comment]
hmm? Submodule is definitely .net 7
or do you mean Naudio?

**Comment by wolfcomp** [comment]
NAudio is the culprit.

**Comment by goaaats** [comment]
Ah right, I looked at the wrong commit, my bad

**Comment by goaaats** [comment]
This is not gonna work unless we add the WindowsDesktop ref assemblies to plogon, I wonder why it built before? Might be new with .net7?

**Comment by Limiana** [comment]
It have never built before with D17, I always just sent it to old repo (and Mini too)

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by Limiana** [comment]
cool, thanks!

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
