### PR TITLE
CurrencySpender Release

### PR DESCRIPTION
**Pull request by Blackcatz1911**
A plugin to display where/how to spend your currencies.
Currently supported:
- GC Seals
- Peotics
- Wolf Marks
- Tomestone of Aesthetics

/cur To open the main window.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon! It may take a while as we are still working towards a public release of Dalamud for FFXIV Patch 7.1 and API 11 plugin updates.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by Blackcatz1911** [comment]
This is without custom CS, so the builds should work again

**Comment by nebel** [comment]
Current version seemingly cannot load after login because `PlayerHelper.init();` runs before the code in `TickScheduler` executes, which is required to instantiate the `TaskManager` which `PlayerHelper` expects.

**Comment by Blackcatz1911** [comment]
Should be fixed in the v1.0.3

**Comment by philpax** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Currency Spender
 - Plugin loads/unloads correctly
 - No issues noted with functionality

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by Blackcatz1911** [comment]
@catz1911 on discord

**Pull request merged**
