### PR TITLE
[Testing] PartyPlanner 1.4.1.0

### PR DESCRIPTION
**Pull request by edg-l**
New plugin.

Shows a list of user organized events sourced from the partyverse.app API as shown in the image.

image

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Review by philpax — APPROVED** [review]
Thanks for submitting a plugin! If you're in the goat place Discord, let me know your Discord username and I'll have you added to the dev-private channels.

**Comment by edg-l** [comment]
Sure, it's Ryozuki#2188

**Pull request merged**
