### PR TITLE
[Testing] SimonSays

### PR DESCRIPTION
**Pull request by RaylaValdez**
SimonSays listens to only designated chat channels for a specific catchphrase, prior to a valid emote string,
it then checks the string across the games emote list, if matching it then sends the emote command into chat.

SimonSays will _only_ accept emotes. 

SimonSays has a working but minimalistic configuration window, which from there the user can specify all options and conduct testing of their options.

### CODE REVIEW

**Comment by reiichi001** [comment]
Hello! 

Can you tell us what this plugin does and provide a description of it in your first post? 

I've also adjusted the PR title to match what's needed to post into the Plugin-Testing-Releases channel.

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by RaylaValdez** [comment]
I've edited my first post to have a brief overview and description of SimonSays

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Pull request closed without merging**
