### PR TITLE
PartyPlanner 1.5.2

### PR DESCRIPTION
**Pull request by edg-l**
- Fixes an issue where some events were not shown.

### CODE REVIEW

**Comment by MidoriKami** [comment]
You don't need to PR the same version to both stable and testing-live.

If stable has a higher version number than testing, users will get the stable version, even if they have testing enabled.

**Comment by edg-l** [comment]
> You don't need to PR the same version to both stable and testing-live.
> 
> If stable has a higher version number than testing, users will get the stable version, even if they have testing enabled.

i see, i didnt know that, do i need to change the pr now however?

**Comment by reiichi001** [comment]
@edg-l can you verify this is good for 6.4 please? If so, we'll merge it in.

**Comment by edg-l** [comment]
@reiichi001 tested and works

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
