### PR TITLE
[Testing] EasyTranslate v1.0.0.0

### PR DESCRIPTION
**Pull request by Olaren15**
This new plugin allows players to search for translations of in-game elements. It uses xivapi to search elements by name and show the users their English, French, German and Japanese names.

This plugin is really useful when playing with people who have their client in a different language!

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Hi there! Sorry for the delay on approving this plugin for review.

It looks like there's [a few issues with the build](https://github.com/goatcorp/DalamudPluginsD17/actions/runs/8223556700/job/22486392376); it looks like you're using C# 12, which we don't currently support. We'll likely add support for that in the future, but it might be easier to use an older version of C# in the meantime.

**Comment by Olaren15** [comment]
Thanks! I'll look at it and try to fix the build errors

**Comment by philpax** [comment]
Hmm, looking into why that failed, will get back to you...

**Comment by NotNite** [comment]
Our build system has a slight flaw that the folder name that contains the manifest in this repository needs to match the internal name of the plugin (EasyTranslate.DalamudPlugin).

**Comment by Olaren15** [comment]
Thanks a lot for the help! The build is working now :)

**Comment by philpax** [comment]
Thank you for finding three bugs in our build system 😅

I've completed the code review and everything looks good, but is it possible to use Lumina instead of XIVAPI for the queries you need to do? Lumina uses the local game files, which should allow it to be lower latency / more reliable.

**Comment by Olaren15** [comment]
I've looked a bit into using lumina to get the translations info, but the advantage of using xivapi is that is searches through almost all of ffxiv's content (items, quests, fates, mobs, achievements, etc...).

From what I understand, if I were to use Lumina, I would have to implement a search function for every Excel sheet. I also presume that I would have to iterate over *every* item in a sheet in order to search by name. Please correct me if i'm wrong.

So yeah I think that using xivapi and its processed/indexed data saves me a lot of complexity 😅

**Comment by philpax** [comment]
Fair enough - yes, I believe you're correct. Happy to leave it as-is then :)

Will continue with the review process, then!

**Comment by philpax** [comment]
All sorted! (tested by @NotNite)

We'd still like to help you switch over to Lumina at some point (including potentially building/shipping a local index), but it's not a blocking concern right now. Just reach out on Discord if you'd like to brainstorm ideas 🙂 

---
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by philpax — APPROVED** [review]

**Comment by Olaren15** [comment]
Thanks a lot for approving and testing my plugin!

I think that moving to Lumina eventually would be a good move and I would appreciate help to make it happen! (I'm still a c# and Dalamud plugins noob lol)
I originally had plans to also make a website that offered the same functionality, but outside of the game (hence the over-separation of the code ^^') but I found out that something like this already existed haha (https://xorus.github.io/xivtrans/)

I would also like to join the dev channel on discord :) my discord username is olaren

**Pull request merged**
