### PR TITLE
[Testing] Voice Director v1.0.0.0

### PR DESCRIPTION
**Pull request by Noevain**
Voice Director is a plugin that allows the player to set preferences as to what language the voices should be based on what duty(content) the player is currently in. Upon exiting the voices will be set back to the default option. 

This changes the CutsceneMovieVoice system config value which is client side and players are already able to change this value mid-instance so this should comply with plugins guidelines.

All feedback is welcome. Thank you!

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Hello! This plugin's been added to our review queue. I have a note while going through the code.

`Dalamud.Plugin.Bootstrap.targets` should already import FFXIVClientStructs, Lumina, and Lumina.Excel because it pulls in `<Import Project="$(DalamudLibPath)/targets/Dalamud.Plugin.targets"/>`. AFAIK, you don't need to specify those on your project manually and they can be removed from your csproj.

**Comment by Noevain** [comment]
Noted, I think I added them because I had some missing namespaces in VS when cloning the project for the first time but I just tested and it works so I'll remove them from .csproj. Thanks.

**Comment by reiichi001** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by reiichi001 — APPROVED** [review]

**Comment by Noevain** [comment]
Thank you, my discord handle is noevain

**Pull request merged**
