### PR TITLE
[Testing] update scout helper to v0.2.0.0

### PR DESCRIPTION
**Pull request by dit-zy**
this is a somewhat big update because i got tunnel vision and didn't try to release more incrementally >_< (i will do that going forward!)

* there are some substantial UI additions, and a large amount of supporting code
* added a new copy mode allowing copying of a whole template with variables
* adding zw3lf as an owner, given that we are collaborating a lot between scout helper and coord importer

### CODE REVIEW

**Comment by dit-zy** [comment]
;-; i don't know what that error means. could it be the `https://example.com` i have as an example in the code?

**Comment by NotNite** [comment]
Sorry about that, Plogon errors aren't the best - I'd suspect it's from the Git submodule you have using Git over SSH. Try switching it to HTTPS.

**Comment by dit-zy** [comment]
ah how interesting! thank you, i fixed!

**Comment by NotNite** [comment]
Uh, interesting! That might be a bug in submodule restoration on the build system. Likely not your fault.

**Comment by dit-zy** [comment]
>_<

i did notice that ottergui has its own submodule for otterguiinternal that is using ssh instead of https. i wonder if that's relevant

**Comment by philpax** [comment]
Huh. That's pretty weird - it looks like the only point of difference that I can see is that Otter has `branch = main` in his `.gitmodules` (<https://github.com/Ottermandias/GatherBuddy/blob/main/.gitmodules>). Can you try that and see if it makes any difference? (I wouldn't expect it to, but...)

**Comment by dit-zy** [comment]
oh interesting. i'll try that next. otter pushed out a change to use https with his own submodule so we're seeing if that works

**Comment by Ottermandias** [comment]
> Huh. That's pretty weird - it looks like the only point of difference that I can see is that Otter has `branch = main` in his `.gitmodules` (https://github.com/Ottermandias/GatherBuddy/blob/main/.gitmodules). Can you try that and see if it makes any difference? (I wouldn't expect it to, but...)

GatherBuddy does not yet use a version of OtterGui that has submodules though.

**Comment by dit-zy** [comment]
bleatbot, rebuild

**Comment by dit-zy** [comment]
bleatbot, rebuild

**Comment by dit-zy** [comment]
closing this PR because it's a mess of changes and i don't want any reviewers to be confused. will open a new one shortly with the final, working commit hash >_<

**Pull request closed without merging**
