### PR TITLE
[Testing] Collections v1

### PR DESCRIPTION
**Pull request by Seventhxiv**
Collections plugin for Dalamud.

Provides an interface to track and discover collectibles.

Glamour, Mounts, Minions and more to come.

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by Seventhxiv** [comment]
> @Seventhxiv Deepest apologies for the delays here.
> 
> Your plugin contains a hardcoded path to your local filesystem and crashes upon startup. In addition, your plugin's internal name in the json file must match exactly the folder you place your manifest in in this repository, case sensitive.
> 
> Please fix these issues so we can proceed with approval, and again, thanks for your patience.

Thanks for taking a look!
Fixed the internal name, and changed the hardcoded path (oops).

Updated with a new hash

**Comment by lmcintyre** [comment]
@Seventhxiv Thanks for those changes, works great now.

The plugin approval team would like two changes to the gear preview feature:
- Please disable the preview when the player enters GPose
- Please disable the preview when the window is collapsed

**Comment by philpax** [comment]
Hi there! We're ready to merge this whenever - are you able to make the requested changes?

**Comment by Seventhxiv** [comment]
> Hi there! We're ready to merge this whenever - are you able to make the requested changes?

Hey, appreciate it, I've been away for the last week so sorry for the delay.

I will make the requested changes and update soon.

**Comment by Seventhxiv** [comment]
> Hi there! We're ready to merge this whenever - are you able to make the requested changes?

All done with the latest update.

**Comment by MidoriKami** [comment]
I highly advise using `GameMain.IsInGpose()` instead of UiBuilder.GposeActive.
UiBuild's parameter is misleading and only checks if the player is in a cutscene.

**Comment by Seventhxiv** [comment]
> I highly advise using `GameMain.IsInGpose()` from ClientStructs instead of UiBuilder.GposeActive. UiBuilder's parameter is misleading and only checks if the player is in a cutscene.

Thx for feedback, changed to use GameMain

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
