### PR TITLE
[Testing] rtyping 0.0.1.4

### PR DESCRIPTION
**Pull request by apetih**
Submits plugin for review and testing.

Adds configurable visual indicators in the party list and/or around the nameplate area whenever a party member also using this plugin is typing in chat. Especially useful for Roleplaying, but can be convenient in general to know when someone is writing a message.

### CODE REVIEW

**Comment by reiichi001** [comment]
Working through testing all the new plugins! (THERE ARE SO MANY)

Minor nitpick, but I noticed certain windows have clipping on the buttons. My guess is this would be worse based on font scaling. I'd recommend either making the window resizable or to ensure it's growing accordingly base on font size. (Another reviewer will go through code, so I haven't looked to check that myself)
image

**Comment by apetih** [comment]
I did see there's quite a lot of new submissions!

I've followed your recommendation and have made changes to make the window sizing not be as strict and allow resizing, since I had not considered different font sizes were a thing

**Comment by philpax** [comment]
Hi, sorry about the delay! This (as well as #1076) actually sparked a little bit of a discussion amongst ourselves - we realised that we shouldn't be uploading local content ID in Dalamud, and we shouldn't let plugins do it either. Is it possible for you to switch to `hash(localcontentid)` or similar so that there's no way to recover the original ID? Once that's done, we're happy to merge :)

**Comment by apetih** [comment]
There it is, hopefully that is all good
Should I change the PR name to reflect the change in version number?

**Comment by MidoriKami** [comment]
> There it is, hopefully that is all good Should I change the PR name to reflect the change in version number?

Yes, because we have a discord bot that reads the PR title and the contents of the first message for posting into our Plugin-Testing-Releases announcement channel.

**Comment by apetih** [comment]
Done! Thanks!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Good to go! I know you mentioned that you were doing some testing - are you happy for me to deploy it now?

**Comment by apetih** [comment]
Perfectly happy to do so! I finished the testing before doing the actual commit.

**Pull request merged**
