### PR TITLE
[Testing] Grace Gawker

### PR DESCRIPTION
**Pull request by mashirochan**
First time ever doing this, hopefully I did it correctly!

Grace Gawker is a plugin that attempts to approximate the amount of EXP remaining on your Gatherer or Crafter's Grace buff. It simply watches for experience earned whilst gathering and crafting, and decrements that from a running remainder of EXP.

I'd appreciate any and all feedback, especially in terms of the code itself and any stability/performance improvements that may need to be made - thank you!

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by mashirochan** [comment]
Woohoo! Am I allowed to update the commit during the review process, or should I leave everything be until the review process is finalized?

**Comment by philpax** [comment]
Yup, go for it! It takes some time for code review to be done, and we'll re-review any updates, so no worries from our end.

**Comment by Lerofni** [comment]
Hi! 
I tested your plugin and here is what I found 

* Loads and unloads cleanly
* No Validation Issues
* Display Settings for Hide for Wrong Jobs only seems to work when there is an active Grace. 
* Grace tracking generally seems to work and even works between reloads

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Thanks for testing! That's sufficient for us to continue. 
---
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by mashirochan** [comment]
My discord handle is simply "infiniti" - thank you so much, I'm so excited
ahah!

**Pull request merged**
