### PR TITLE
[Testing] Malmstone Calculator 1.0.0.0

### PR DESCRIPTION
**Pull request by pinapelz**
A plugin that calculates how many matches of different PVP modes you have to play before reaching a certain series level in the current PVP Series

### CODE REVIEW

**Comment by philpax** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Hmm, not sure why that build's failing. I'll try to get someone to look into it!

---

This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by pinapelz** [comment]
Got it to work. Read https://github.com/goatcorp/Plogon/issues/59 and saw that the folder name has to match InternalName

**Comment by pinapelz** [comment]
Not sure if its too late to add to the initial release since I know the code review has already happened.

Been using the plugin myself for the past week and felt like it was missing a few useful features:

- Added option to show toast notification detailing current Series Level EXP progression after PVP Matches
- Added option to show number of matches remaining until next Series Level in chat after PVP matches
- Added option to automatically open plugin window when viewing Series Malmstone Rewards

Let me know if I should revert to the commit which the code review was done on

**Comment by philpax** [comment]
Nope, that's fine! Diff: https://github.com/pinapelz/ffxiv-malmstone/compare/50877adf4583874381fb11f998e4f53abe8f6b4b..ca69aaaa1c242adcba5fc5b96d49c5817b37055c

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Tested by @sersorrel, all seems to work well.

---
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by pinapelz** [comment]
Thanks! My Discord is @pinapelz

**Pull request merged**
