### PR TITLE
Quiet the Den 1.0

### PR DESCRIPTION
**Pull request by xorelcodes**
Frist plugin, let me know if anything needs to be changed!

### CODE REVIEW

**Comment by philpax** [comment]
Hi! Thanks for submitting your plugin - new plugins will take some time to get to as we're clearing out the updates for API11, but we hope to have you sorted out soon 🙂 

We're looking into why your build failed and will hopefully have a fix for you soon.

**Comment by xorelcodes** [comment]
Did a look after realizing maybe putting this all together at 1am wasn't smart, noticed I didn't update the csproj file so I went ahead and did that and found a few things to cleanup like the sample namespace still being used. Didn't want to just do a different pull request but I have a new commit id here if this helps

272365883b313022189374415e8e0cd44a6f10f1

Thanks!

**Comment by philpax** [comment]
You can edit the manifest in this PR to change the commit ID; an easy way to do that is from within GitHub itself, where you can edit individual files. Feel free to update the PR 🙂

**Comment by xorelcodes** [comment]
It's such a simple thing, but i was like...something looks off lol

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Test Results:
Loads/unloads fine
BGM is muted as advertised

**Comment by reiichi001** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
