### PR TITLE
Add AFKMute to testing/live.

### PR DESCRIPTION
**Pull request by wompscode**

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by wompscode** [comment]
Happy to see that it successfully passed building on your guys machines. (was incredibly nervous that there was gonna be some super random unexpected hitch that I'd have never caught otherwise)

Tested it on patch 7.11 and it is still fully functioning as intended.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by Critical-Impact** [comment]
Test Results:

Loads/unloads fine
Muting/unmuting works fine
Only issue I could see and I'd say it's pretty rare but if the plugin is reloaded while you are AFK(auto updating) when you go out of AFK the plugin will not pick this up.

**Comment by wompscode** [comment]
I hadn't actually considered the possibility of the plugin reloading at all, but I could probably fix that in a future update through a config flag that stores the previous state perhaps.

For now, it functions as intended.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by ampheebyan** [comment]
Thank you! It is just `womp` on Discord.

**Pull request merged**
