### PR TITLE
RetainerSales Initial Evaluation

### PR DESCRIPTION
**Pull request by Populo**
Simple plugin to mark retainers that have sold things while you were offline because i can never remember the numbers for sale. Please let me know if something isn't up to par!

image

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by Populo** [comment]
bleatbot, rebuild

**Review by ackwell — DISMISSED** [review]

**Comment by Populo** [comment]
If I may offer advice for testing (how I did it). Open the retainer list to generate the dictionary in the config file and change the numbers there. Have to close the game and reopen to get it to read the changed values tho, couldn’t make it read the file every time.

**Comment by Critical-Impact** [comment]
Retainer Sales
 - Plugin loads/unloads correctly
 - I haven't sold anything recently so can't test functionality

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin added to the main Dalamud plugin repository!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by Populo** [comment]
That would be cool! Discord is @populo
________________________________

**Pull request merged**
