### PR TITLE
[Testing] Hunty 0.6.0

### PR DESCRIPTION
**Pull request by Infiziert90**
I already submit this to the repo as the size is a bit bigger. 
Most of the changes come from my json rework, the true diff should be around 800ish additions and deletions when excluding json stuff.

+ add memory tracking (thanks Midori)
+ remove old tracking completely
+ redo monster.json for new tracking
+ open duty finder on location click
+ react to login/relog
+ prevent null exception with no gc
+ cleanup

- Support all global languages
- UI localization, currently supported languages en, de, fr, jp
- Add small indicator if rank / area is done
- More location updates

### CODE REVIEW

**Comment by MidoriKami** [comment]
Specifically require 2856060e936f23b074635b36197c11e583432cdc or Newer.
Feb13 CS commit

**Comment by Infiziert90** [comment]
bleatbot rebuild

**Comment by Infiziert90** [comment]
bleatbot, rebuild

**Comment by Infiziert90** [comment]
Can be merged now, stable got the CS update

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
