### PR TITLE
[Testing] QuickMaths 1.1.3 

### PR DESCRIPTION
**Pull request by centizen**
Hi team! 

I really wanted an addon that would let me just type simple math expressions into my chat box and get the answer back, without having to mess around with an extra calculator window. I couldn't find anything like that so I decided to make it. Wasn't really planning on submitting it, but other people seem to really like/want it and I figured I'd put it in. 

https://github.com/centizen/quickmaths 

Please let me know if I need to adjust anything to better fit the pipelines.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
This plugin is now in the plugin review queue; we hope to get back to you soon!

**Comment by lmcintyre** [comment]
Hi, sorry about the delay @centizen. Could you remove your Configuration class if you're not using it? Thanks.

**Comment by centizen** [comment]
> Hi, sorry about the delay @centizen. Could you remove your Configuration class if you're not using it? Thanks.

Sure thing, just won't be able to get to it right away since I'm approaching finals at the moment. Will get that done as soon as I can though! 

Thanks!

**Comment by philpax** [comment]
Hi there! Just checking in on this - would you be able to fix up that config? We're trying to get all of the pending plugins in before 6.4 🚀

**Comment by philpax** [comment]
I'm going to close this as it has not seen any activity in a while and there have been several game updates since. Feel free to open a new PR to bring it back up to date if you'd like!

**Pull request closed without merging**
