### PR TITLE
[Testing] ChatProximity 0.0.6

### PR DESCRIPTION
**Pull request by iv230**
Chat Proximity is a plugin designed to enhance the realism and immersion of in-game communication by dynamically altering the visibility of chat messages based on the physical distance between players.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by reiichi001** [comment]
Hello! I've added this plugin to our review queue. New plugins may take some additional time to review compared to plugin updates as they go through a more rigorous process. We hope to be in contact soon!

**Comment by KazWolfe** [comment]
Please consider either removing chat message/player name logging, or if it’s necessary move it to verbose. As is, this can pose a slight privacy problem if a user were to ask for support and have debug logs enabled (which quite a few do).

(Note: I’m not PAC, just a concerned dev)

**Comment by reiichi001** [comment]
Not a blocker for approval, but a couple more things you'll want to clean up as a plugin built from SamplePlugin.

1. If this won't have a main UI window (which makes sense as it's for chat and has a settings window), you'll want to remove that from your code.
2. Rename the project folder from SamplePlugin to ChatProximity or so. (IDEs probably won't do that for you. ...you'd have to edit the text in your solution file and rename the folder yourself - but this is more a nitpick)

**Comment by iv230** [comment]
Thanks for those comments, I updated in consequence :)

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the `XIVLauncher & Dalamud` Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
