### PR TITLE
[Testing] G4EUkrChatSupport

### PR DESCRIPTION
**Pull request by justscribe**
A small plugin to replace ukrainian specific characters in game chat window.

### CODE REVIEW

**Comment by reiichi001** [comment]
Hello! I've updated our tracking for the plugin review team with this PR.

**Comment by justscribe** [comment]
😞

**Comment by lmcintyre** [comment]
Hello, sorry for the wait. As an update on the plugin review end, I have reviewed the code and verified the plugin works. @justscribe, Would you be able to increase the size of your configuration window? Some text gets cut off because it is too small.

**Comment by justscribe** [comment]
Hi @lmcintyre,
Thank you for your review.
About config window, on my environment it looks ok.
зображення
Can you make a screenshot to show how exactly it was cut off?
Thank you.

**Comment by lmcintyre** [comment]
Ahh, it is larger because I am using the "AXIS Font" setting in Dalamud settings.
This is what it looks like for this setting:
image
This is a popular option, so I think it would be nice to make the window just a little bit wider. `Vector2(320, 115)` works well for me:
image

Thanks again.

**Comment by justscribe** [comment]
@lmcintyre fixed.
Thanks for testing.

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
