### PR TITLE
[Testing] BozjaBuddy

### PR DESCRIPTION
**Pull request by kaleidocli**
Bozja Buddy hopes to provide an easier way to look up info related to Bozja/Zadnor content and is heavily inspired by the GUI design of Garland Tools / Gather Buddy plugin (by Ottermandias).

Featuring filterable tables of Lost actions, FATEs, Critical engagment, Duels, Fragments, as well as trailing tabs to provide additional info on the subject (e.g. FATE chains, loot tables, map-linking location, FATE overview, etc.)

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by philpax** [comment]
@tommadness tested BozjaBuddy and it failed to load for him:
```
2023-02-20 16:41:12.768 -05:00 [INF] [PLUGINM] Dev plugin failed to load, adding anyways: BozjaBuddy.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at SamplePlugin.Plugin..ctor(DalamudPluginInterface pluginInterface, CommandManager commandManager, DataManager dataManager, GameGui gameGui) in /work/repo/BozjaBuddy/Plugin.cs:line 52
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 422
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 879
```

**Comment by tommadness** [comment]
Hi, I tested this plugin for the PAC. Everything seems to be in order, I just have two minor nitpicks:

Default window size hides quite a bit of information
Text wrapping in the Description tab would be appreciated

**Comment by kaleidocli** [comment]
Hi @tommadness , thank you for your effort!
- For the description tab I wrapped it in a later version.
- For the window size, I tried to expand it as much as I can but I think there's too many info to display and I don't want users to spare one-third of their screen for my plugin. I also add a compact mode in a later version to address this issue.

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
Congratulations on your first plugin!

As a first-time contributor, if you're in the XIVLauncher & Dalamud Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Pull request merged**
