### PR TITLE
[Testing] NoTankYou v5.0.0.2

### PR DESCRIPTION
**Pull request by MidoriKami**
Total internal rework, everything should function the same, but better.

All configurations are now per-character, your old config will be copied to each of your characters.

image

### CODE REVIEW

**Comment by MidoriKami** [comment]
There were no added nor removed features in this version, just system reworks.
User configs won't actually be wiped, they will just be ignored. I'm switching from using NoTankYou.json to using LocalContentID.json inside the `pluginConfig\NoTankYou` folder. As such, a user could revert from testing to get their configuration back.

The new design makes it very easy to add new modules, so in the coming days I will be adding some more features.

**Comment by philpax** [comment]
This is a pretty big diff so won't be able to review it for a bit - would suggest using that time to figure out a migration story

**Comment by lmcintyre** [comment]
I can't say I know much about what there is to configure for NoTankYou; however; I would recommend migrating as well. Even if it's as simple as "copy old config to all characters" kind of thing. Otherwise people will generally be very upset. If you are fine with that, we can't hold you back from your decision though.

**Comment by MidoriKami** [comment]
I've already been working on it.

**Comment by MidoriKami** [comment]
There done. That should make everyone happy.

**Comment by MidoriKami** [comment]
Added PartyListOverlay preview mode, there will be no more changes for this PR.

**Review by lmcintyre — APPROVED** [review]

**Pull request merged**
