### PR TITLE
[Testing] RpUtils

### PR DESCRIPTION
**Pull request by KassWasTaken**
# RpUtils
RP Utils intends to provide a suite (eventually) of features to support roleplay, by connecting to RpUtils servers. Currently, it only adds an RP Sonar feature. Future (distant) plans include custom items and inventory, custom quests, group combat systems, and integrating with other relevant plugins and systems to facilitate open world roleplay.

## RpSonar
RP Sonar, when enabled and the user is currently /roleplaying, will anonymously submit the players position to RpUtils servers. This anonymous position data is collected and organized into a cache along with other users. Users can open their map (regardless of /roleplaying or not) to search for other roleplayers nearby, or in other zones.

### CODE REVIEW

**Comment by reiichi001** [comment]
bleatbot, approve

**Comment by KassWasTaken** [comment]
Hey @reiichi001, wanted to check to see if there was an idea when there would be movement on this? No rush, of course.

**Comment by reiichi001** [comment]
Hi @KassWasTaken, normally code review has to be completed before we move onto testing. Regarding testing though, I heard that this service will require login credentials. Is there a test account that we could use for review purposes?

**Comment by KassWasTaken** [comment]
There is no login required currently, no. It only reports anonymous position data when enabled and /roleplaying to a server which aggregates the data to help make open world RP more discoverable. 

I do have plans down the road that will require some form of identity, but that won't come until XivAuth is off the ground.

Regarding the code review, is there anything left I need to take care of before that process begins?

**Comment by reiichi001** [comment]
> Regarding the code review, is there anything left I need to take care of before that process begins?

No, we just need a plugin review member who has time to go through it.

**Comment by KassWasTaken** [comment]
Gotcha, thanks! If there's anything I can do to help with the process or questions to answer, please let me know!

**Comment by philpax** [comment]
Hi there, I've looked over the code and it looks good - we should have testing and rules compliance done soon 🙂 

The only thing I wanted to mention is that you may want to rename "Sonar" - there's already a plugin by that name and it may potentially be confusing. I'm not sure how much overlap there is in users, but it might be large enough to cause issues. This isn't a requirement - you can keep it if you'd like - but I figured I'd give you a heads-up.

**Comment by KassWasTaken** [comment]
> Hi there, I've looked over the code and it looks good - we should have testing and rules compliance done soon 🙂
> 
> The only thing I wanted to mention is that you may want to rename "Sonar" - there's already a plugin by that name and it may potentially be confusing. I'm not sure how much overlap there is in users, but it might be large enough to cause issues. This isn't a requirement - you can keep it if you'd like - but I figured I'd give you a heads-up.

Is this referring to the hunt sonar? Or is there another sort of RP sonar out there? Given its more so a name of a feature rather than the plugin I'm not immediately scared off by it, but I'll give it some more thought. Eventually I do intend to add more features to this as well, but that will have to be much further down the road.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
I ran through a test install for review and can load the plugin, its settings window, and can enable the options, but I'm not sure if there's supposed to be a save button or if they will enable at time of click.

Since I'm over on Balmung, there are generally plenty of people with RPer status enabled, but I didn't see any changes to the map. Could you elaborate on what a player should see when the RP Sonar's enabled / show a sample screenshot please? (If this is more a case of the web service being down, please let me know if/when up and I can retest.)

**Comment by KassWasTaken** [comment]
> I ran through a test install for review and can load the plugin, its settings window, and can enable the options, but I'm not sure if there's supposed to be a save button or if they will enable at time of click.
> 
> Since I'm over on Balmung, there are generally plenty of people with RPer status enabled, but I didn't see any changes to the map. Could you elaborate on what a player should see when the RP Sonar's enabled / show a sample screenshot please? (If this is more a case of the web service being down, please let me know if/when up and I can retest.)

@reiichi001 The setting changes take effect at the time of click. As for the changes to map, it does not show all players around you with /roleplaying enabled, it only shows other players that are also using the plugin and /roleplaying. You might be able to find some of the people that were helping testing it at the bloodsands (outside Ul'dah). I can also hop on some time to help with testing if that works?

Here is an example of what it might look like. 
image

**Comment by KassWasTaken** [comment]
I think there is a bug at the moment in regards to looking at other zones you're not currently in, the markers don't seem to be showing properly, but if you travel to that zone and refresh map they will. Still working on narrowing that down, but I don't view it as a blocking defect for the moment.

**Comment by reiichi001** [comment]
OK, so the collected data is only from other players who are also using the plugin with that feature enabled. I was under the impression that it was grabbing any qualifying players. The current functionality checks out in this case. 

We're just waiting on a couple more plugin reviews to cast their votes (it's got the minimum required to pass, but I'd like to get opinions from the other reviews on any potential concerns, which I'll give till morning-ish PDT), but I think all is in order for merge.

If you're in the XIVLauncher & Dalamud Discord server and would like to get access to the private developer channels for plugin feedback and others, please let us know your Discord handle and we'll grant you the role.

**Comment by KassWasTaken** [comment]
Yep, correct. I know there is some concern over this potentially being used to pinpoint people using mods given its only people using the service. I have some ideas on how to tackle this as well to provide a bit more plausible deniability while still providing value to its users, but I'll likely implement that in a future update since I'm hoping to get some feedback on the current functionality first.

Glad to hear though! Thank you for the time and energy to review it. I appreciate all of ya. As for discord, my id is `kasserole`

**Comment by philpax** [comment]
> > Hi there, I've looked over the code and it looks good - we should have testing and rules compliance done soon 🙂
> > The only thing I wanted to mention is that you may want to rename "Sonar" - there's already a plugin by that name and it may potentially be confusing. I'm not sure how much overlap there is in users, but it might be large enough to cause issues. This isn't a requirement - you can keep it if you'd like - but I figured I'd give you a heads-up.
> 
> Is this referring to the hunt sonar? Or is there another sort of RP sonar out there? Given its more so a name of a feature rather than the plugin I'm not immediately scared off by it, but I'll give it some more thought. Eventually I do intend to add more features to this as well, but that will have to be much further down the road.

Yep - shouldn't pose an issue if you're OK with it, just wanted to call it out!

**Review by philpax — APPROVED** [review]

**Comment by philpax** [comment]
We have consensus! Congratulations on your first plugin :)

**Pull request merged**
