### PR TITLE
[Testing] DcNotify

### PR DESCRIPTION
**Pull request by RaidenvBlack**
A Dalamud plugin to send a Discord Webhook Message to your Server whenever a Party Finder event or duty pop happens with an AFK client.
I made it because Discord is getting used by the most People and the Discord Webhook is easy to use and to setup.
This Plugin uses much from PushyFinder/Ntfynder repository.

### CODE REVIEW

**Comment by philpax** [comment]
Hi, thanks for the submission! @ackwell will take this through the plugin approval process 🙂

**Comment by philpax** [comment]
Could you move the plugin to testing? Our policy is to have new plugins in testing so that they can be tested for any obvious issues before they go out to a wider audience.

**Comment by RaidenvBlack** [comment]
Yes sure i am sorry. Moved it now to test.

**Comment by RaidenvBlack** [comment]
@philpax Do you know how long this plugin approval process take ?

**Comment by ackwell** [comment]
usually not this long - sorry, i forgor, mb

i'll have a look after work; but in the meantime - you note that much of it is from an existing plugin that's in the plugin repository already. if that is the case, have you considered submitting your changes to that directly rather than introducing a separate new plugin?

while there's def. some degree of repetition within the plugin repository, that's not something to strive for.

**Comment by RaidenvBlack** [comment]
I would like to add different features to that plugin in the future and i think it is better to make it to a new Plugin and maintain it by myself.

**Comment by RaidenvBlack** [comment]
@ackwell Did you forget about it again?

**Comment by ackwell** [comment]
No, it's just been a very busy week. Code looks fine.

I have diffed this with ntfy and pushy variants and at this point... two was manageable, but three is getting a little silly, sorry. I understand you may wish to add further functionality in future, but that's not here now, so I can't make decisions based on it.

With what we have here right now, this would effectively involve a third near-identical plugin in the repository.

Looking at the current deploy states, it would seem that pushy is on stable, but ntfy is only on testing at the moment. This poses a good opportunity to merge these (now 3) plugins into one, preferably the one that's already got adoption on stable.

cc @Arcadia64
cc @lostkagamine

Can I ask you two and @RaidenvBlack to coordinate how you wish to proceed? No preference from my side on how you tackle it, be that passing maint, shared maint, or other solutions. I'd just rather not introduce further fragmentation of this project.

**Comment by lostkagamine** [comment]
I'd have appreciated if anyone made _any_ effort to contact us before beginning to work on a plugin functionally identical to ours. Please reach out to us on Discord; we're in the XL discord as Nightshade System (@/system.runtime.interopservices).

**Comment by lostkagamine** [comment]
> I would like to add different features to that plugin in the future and i think it is better to make it to a new Plugin and maintain it by myself.

Please don't do this. We're open to work with you to add those features, I just don't see the point in adding an entirely separate plugin; it'd just create confusion in my eyes.

**Comment by RaidenvBlack** [comment]
@lostkagamine okay then I will give it a look and try to add it to your existing Plugin. @ackwell Thank you for your answer.

**Comment by lostkagamine** [comment]
@RaidenvBlack Please reach out to us on Discord (we're present in the XIVLauncher server as 'Nightshade System') for further coordination.

**Comment by philpax** [comment]
Hi, just checking in on this - have you been able to coordinate?

**Comment by RaidenvBlack** [comment]
Yes I will merge my part in to the existing PushyFinder Plugin from @lostkagamine  when I find time for it.

**Comment by philpax** [comment]
Hiya, I'm going to close this for now. Please feel free to reopen this once a conclusion has been reached!

**Pull request closed without merging**
