### PR TITLE
CurrencyAlert v2.2.0.2

### PR DESCRIPTION
**Pull request by MidoriKami**
API11

I expect no issues with this one.

### CODE REVIEW

**Comment by MidoriKami** [comment]
No idea why the build is failing, log suggests some kind of internal build error with packager.

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by MidoriKami** [comment]
It definitely builds locally for me, I genuinely don't know what the problem could be. NoTankYou seemed to report the same issue, seems like it failed to build once after it was merged, but then seemed to build fine afterwards.

**Comment by goaaats** [comment]
This must be an issue in DalamudPackager caused by the new SDK, in connection to libs. Not 100% sure how to solve it yet but I'll look at it tonight. We might have to have a permutation of Dalamud.NET.Sdk that doesn't include DalamudPackager.

**Comment by MidoriKami** [comment]
I just don't know why it would work for my other plugins and not this one, I'm not aware of doing anything differently here.

**Comment by MidoriKami** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by reiichi001** [comment]
bleatbot, rebuild

**Comment by MidoriKami** [comment]
Removed dalamud.NET.sdk from KamiToolKit, and KamiLib.
I very much would have preferred to keep using the sdk for these projects.

**Review by reiichi001 — APPROVED** [review]

**Pull request merged**
