### PR TITLE
added Oh Gee, CD 0.0.22 to testing

### PR DESCRIPTION
**Pull request by rootdarkarchon**

### CODE REVIEW

**Comment by goaaats** [comment]
bleatbot, rebuild

**Comment by goaaats** [comment]
bleatbot, approve

**Comment by philpax** [comment]
Build's broken as you're using `net6.0-windows` (which we can't build)

Once you switch off that you'll have issues with sound - you can fix that with NAudio, as kal did here https://github.com/goatcorp/DalamudPluginsD17/pull/567

**Comment by Caraxi** [comment]
> Build's broken as you're using `net6.0-windows` (which we can't build)

Can't build `net6.0-windows`?
Every other plugin using `net6.0-windows` disagrees

**Comment by philpax** [comment]
ping, any luck sorting this out?

**Comment by rootdarkarchon** [comment]
I'll close it until i get time to actually fix the issues.

**Pull request closed without merging**
