### PR TITLE
[Testing] Test out new DalamudPackager version

### PR DESCRIPTION
**Pull request by reiichi001**
nofranz
Don't actually merge this. Or do merge it. I know you actually want to merge it.

### CODE REVIEW

**Review by KazWolfe — APPROVED** [review]
Approved for mainline and auto-install to all Dalamud users.

**Comment by reiichi001** [comment]
> Approved for mainline and auto-install to all Dalamud users.

Well it needs to build successfully first.

**Comment by Koenari** [comment]
You should rebuild the project locally to fix the lockfile. The contentHash for 2.1.9 resolves to "raxjlbAWAt9AYXTiRlRJOHHFOraNicVsPJXlFQEzx+Ym2Imh990llQ5bQ+DACVGgy65+axVnlL9QwkKspY5yzQ==", if you wanna fix by hand.

**Comment by reiichi001** [comment]
> You should rebuild the project locally to fix the lockfile. The contentHash for 2.1.9 resolves to "raxjlbAWAt9AYXTiRlRJOHHFOraNicVsPJXlFQEzx+Ym2Imh990llQ5bQ+DACVGgy65+axVnlL9QwkKspY5yzQ==", if you wanna fix by hand.

`uusetrIitwYN0mHAud/UFeOYy3bh11+iSGjUGIGSm3k03m9hiYgKji7Pn/Z3egr5FgJjXAKUCLrVTaXE12Tmkw==` is what VS spits out when I build locally, including removing it from the project and re-adding it from NuGet. 

This isn't an actual plugin merge request so much as the spot check to make sure DalamudPackager 2.1.9 is working as intended. Because if it's going to fail on a tiny plugin like this one, then it'll cause issues for any other plugin too. I had to completely purge my nuget cache on the machine to force it.

**Comment by reiichi001** [comment]
Closing PR because build artifact shows the DalamudPackager changes are good now.

**Pull request closed without merging**
